alisw/ali-bot

build-ib.sh

Changes related to the GAR builder.
* Optionally drop to shell with `--drop-to-shell` after fetching the recipe. This is only used manually for debug.
* Support recipes where the software to be built resides in a software group with a different name. This is not the case with, *e.g.* **AliRoot** (where the recipe is under `apps/aliroot/aliroot`), where it is still sufficient to specify `--software aliroot` to build it. It is however the case with, *e.g.* **Geant4 VMC**: the recipe is under `apps/geant4/geant4_vm`; it is now possible to build it by specifying `--software geant4:geant4_vmc`.

GAR builder: more debug options and support for exotic recipes

---

schedule.py

We need to clean up ancient ini file, for the case in which the script is
executed from the same place twice in a row.

Fix issue when the ini file is not there.

---

config.yaml

Address the fact we currently do not have ubuntu builders.

---

config.yaml

The scheduling logic cannot distinguish between aliroot-test ROOT5 and
aliroot-test (ROOT6). This works around the problem. The correct solution would
be to include the alidist / aliroot tag in the name of the scheduled entity.

Only build aliroot, not aliroot-test for root6

---

config.yaml
schedule.py

This excludes already built tags by tag name. Not sure how it could work
before, but adding the alibuild and alidist property to the payload
triggered infinite rebuilds without this.

Fix continuos rebuild issue

---

aliPublish

Fixes problem spotted today.
AliEn was down, and `packman list` returned an empty set, forcing the publisher to re-publish every single package.
Of course since it was down, every single publication failed.
We now avoid this waste of time by checking heuristically and ahead of time if the AliEn API returns a meaningful and known result to a simple request.

Publisher: check if AliEn works before publishing

---

logstash/logstash.conf
logstash/to_monalisa.conf
script/get_builds.sh
script/set_mappings.sh

This frees up data nodes from responding to queries, hopefully improving
the reliability of the system.

Move to use elasticsearch-client

---

upload-bintray-distribution

- Specify APT repositories extra properties.
- Add ability to specify the repository format in the configuration file.

Fix to work with Ubuntu bintray repositories

---

aliPublish

Backwards-compatible for packages with no dist-runtime

Publisher: consider runtime dependencies

---

publish/aliPublish

Using a single "alien find" rather than an "alien ls" per package.
Thanks Miguel Martinez Pedreira!

Publisher: much faster check if installed on AliEn

---

riemann/riemann.config
riemann/ws_config.json

Fix a stupid mistake which created one stream per changed property, rather
than just one with edited fields.
TTL of build_warning and build_errors is now 3600 seconds.

Improved build_warning and build_error events

---

riemann/riemann.config

Most of the monitors report to slack when a given threshold is passed or there is a state change.

Introduce a few monitors for Mesos / Marathon using Riemann

---

riemann/riemann.config

Compute mesos slave/health metric and send a Slack message when it expires,
meaning the Mesos Master unregistered it.

Complain when mesos slaves go MIA

---

riemann/riemann.config

Notify slack if the number of instances for an app drops to zero.

Monitor Marathon apps

---

publish/aliPublish
publish/aliPublish.conf

* Riemann disabled on dry runs
* Notify all ALICE only on new AliRoot/AliPhysics
* Notify experts only for the rest, and in case of errors

Improve notifications

---

publish/aliPublish
publish/aliPublish.conf

Some hosts where aliPublish runs cannot be configured to use Mesos DNSes. This
feature adds a new configuration variable, `mesos_dns`, with a list of Mesos DNS
hosts. If a hostname in the configuration ends with .mesos, an attempt to
resolve it to IP using the [Mesos DNS API](https://mesosphere.github.io/mesos-dns/docs/http.html)
is made.

Support for Mesos DNS API in aliPublish

---

publish/aliPublish

A temporary connection failure might be the cause of dist-runtime unavailable.
In this case, considering all dist packages as runtime dependencies as fallback
is wrong and dangerous, as it could cause (as it happened) dozens of temporary
packages being unintentionally published. Now if the URL is not accessible (i.e.
if we cannot get the list of runtime dependencies for a given package) the
package is simply skipped. In case of a temporary server error a subsequent run
should recover.

No fall back on dist when dist-runtime fails

---

jenkins/release-alibuild

Support multiple tags for same commit when releasing alibuild.
Only the last one will be used.

Improve alibuild-release process

---

auto-update-git-branches

As discussed in alisw/alidist#337, we need to derive the root6 branch from next, so that it can be useful also for O2 developments.

Make .*/root6 branch derived from .*/next

---

jenkins/build-coverage

This pipeline will download and build AliRoot using the coverage
defaults so that code coverage compilation options are added.
The results should be published in the gitlab repository
aliphysics-coverage and then published to ali-ci.cern.ch.
This is the initial work to get that done.

Add build-coverage pipeline

---

Jenkinsfile

This test checks various aspects of the `alienv` script used on CVMFS before putting it in production.
Tests run:
* `alienv enter`, `alienv printenv`, `alienv setenv`
* Check if legacy `AliEn` package can be loaded as a standalone
* Check if the correct `g++` compiler is loaded on all supported platforms (covering legacy case using system's one)
* Check if the correct `aliroot` is loaded on all supported platforms
* Check if the correct `AliEn` is loaded on all supported platforms (covering legacy case using `AliEn` in place of `AliEn-Runtime`)

Add Jenkins test for alienv

---

publish/aliPublish

AliEn PackMan might silently return zero packages from time to time. This is now considered an error condition and does not trigger any longer the republishing of all packages.

Add check to AliEn PackMan output

---

jenkins/deploy-cluster-updates

- Use the `git` step, to simplify getting the credentials.
- Improve readibility by using the `ansiblePlaybook` step.

Bring deploy-cluster-updates back in business

---

publish/aliPublish.conf
publish/test.yaml

They are dependencies of AliGenerators.

Remove POWHEG and Rivet from direct publishing

---

ci/continuous-builder.sh

Now that we have revocable resources in Mesos, we can actually afford of
to keep building things as if integration was continuously happening. In
case something urgent comes up, the resources will be reappropriated by
the production jobs.

Add script which does a continuous build

---

ci/continuous-builder.sh

- ALIBUILD_REPO to configure where to pick up alibuild
- ALIDIST_REPO to configure where to pick up alidist
- Do not die if build fails.
- Use reference sources
- Fix AliPhysics -> AliRoot typo

Improve aurora based continuous integration

---

publish/aliPublish-nightlies.conf
publish/aliPublish.conf
publish/test-nightlies.yaml
publish/test.yaml

Also prevents to pollute CVMFS with plenty of useless GCC versions by specifying
a fixed one instead of a broad regexp.

Publish GCC-Toolchain for Ubuntu 16.04

---

jenkins/deploy-hlt-updates

Quotes were missing causing occasional YAML parsing errors.

Fix HLT vault token in inventory file

---

list-branch-pr

Introduces a new helper script `list-branch-pr`, which
allows to list all the pull request for a given branch of
a given repository. Allows passing a `--trusted` option which
can be used to filter pull request based on trusted users.

Add helper to list hashes of open PRs

---

ci/continuous-builder.sh

Introduces a PR_REPO and PR_BRANCH variable which can be used to point
to a branch in a repository for which to test all the available pull
requests. A TRUSTED list of user can also be specified to limit only to
PRs of trusted users.

Test pull requests for the specified repository

---

list-branch-pr

It's now possible to list "trusted" PRs (i.e. those which has a given
status set to success). This comes handy to deal with test of PR coming
from non power users.

Filter PRs by status

---

build-any-ib.sh

From the Jenkins interface it is now possible to specify as source branch a reference in the form `pull/<ID>/head` as described [on the GitHub doc](https://help.github.com/articles/checking-out-pull-requests-locally/).

Add ability to build pull requests

---

cvmfs-mon/cvmfs-mon.py
cvmfs-mon/cvmfs-mon.yml

We now consider the last time the Stratum-0 was updated instead of blindly
computing the difference between time revisions in order to avoid plenty of
false positives.

Improve tolerance on CVMFS delays handling

---

cvmfs-mon/cvmfs-mon.py
cvmfs-mon/cvmfs-mon.yml

Current logic matches the one from the webpage[1]. Service is considered:
* OK if Stratum-1 and Stratum-0 have the same snapshot
* Syncing if Stratum-1 is behind less than `max_revdelta` revisions and
Stratum-0 changed less than `max_timedelta` seconds ago
* Error if Stratum-1 is outdated, either too many revisions or more than
`max_timedelta` seconds
Logic introduced by #359 is fine but way too tolerant: in the case of the ALICE
OCDB for instance updates are very frequent so notifications were never
triggered even if the Stratum-1 was too many revisions behind.
[1] http://cernvm-monitor.cern.ch/cvmfs-monitor/alice-ocdb.cern.ch/

Improve CVMFS monitor notify logic

---

daq-da-rpms.sh

External Vc is too recent and requires C++11, which is not allowed by SLC6
compiler (DAQ requirement).

Disable Vc in daily DA RPMs

---

docker-compose.yml

- Set MESOS_SWITCH_USER to false since in any case we run everything
from inside a docker container.
- Set MESOS_DOCKER_MESOS_IMAGE properly to make sure mesos can correctly
recover jobs.
- Use environment variables to configure marathon

Cleanup mesos configuration

---

publish/aliPublish
publish/get-and-run.sh

JSONs coming from URLs containing dependencies that never change are cached on
disk if the optional `--cache-deps-dir` parameter is supplied.

Add caching to aliPublish

---

publish/aliPublish.conf
publish/test.yaml

This reverts #386. We cannot publish that CMake version (missing modulefile).

Do not publish CMake any longer

---

report-pr-errors

This way we can retrieve the full logs in case a PR is broken.
Comment message also changed to point to the full log.

Copy build logs to web store

---

ci/continuous-builder.sh

This should solve the infamous "PR check takes ~20 minutes" reports.
What was happening is that in order to ensure consistency of the builds
we triggered a full rebuild of development packages for each pull
request. This makes sense in the case of alidist pull requests because
you could have non-trivial interpackage dependencies like "use ROOT6
rather than ROOT5" which would fail miserably if short-circuited, at
least in the generic case. This is however not the case for AliRoot /
AliPhysics PR, where make / CMake takes care of the consistency for us
making the extra rebuild unneeded.

Short-circuit consistency tests for PR

---

report-pr-errors

Rather than parsing comments to see if we have a new error to report,
we encode the error as part of the the issue title, so that we can
immediately spot if something needs to be changed. This should
spare us a few API calls.

Do not parse comments when updating branch issues

---

awake-on-http

This will sleep N seconds according to the `-t N` option unless
an HTTP GET request is done, in which case it will terminate early.

Timeout for N second or for an HTTP GET request

---

ci/.gitignore
ci/metagit.py
ci/process-pull-request-http.py

* The `MetaGit` backend now supports "dummy" Git operations on the local disk,
where a pull request status is saved in a YAML file.
* This is triggered by passing the `--dummy-git` flag. Pull request statuses are
read from `<pwd>/dummy/<org>/<repo>/<prnum>/status.yml`, which is never
changed: changes are saved in `update.yml`, which is subsequently read for
further interaction.

Add dummy Git backend for testing

---

make-shuttle.sh

* For both the test shuttle and the production one
* Uses aliBuild
* When building master it falls back to the latest working version in case it
does not compile

Add shuttle aliBuild steering script

---

publish/aliPublish.conf
publish/test.yaml

Analysis tags depending on v5-09-10 and v5-09-11 have to be removed as per
the Physics Board decision. See alisw/AliRoot#332.

Exclude publishing of faulty tags

---

list-branch-pr

Current C.I. mechanism favors untested PRs, and in case no PR is untested, it
retests the first one which failed (or the first one which was reviewed), not
giving any chance to other failed PRs to get retested. This PR mitigates the
problem by picking a random failed (or reviewed) PR instead of the first one.

Pick a failed/reviewed PR to re-test randomly

---

publish/aliPublish
publish/pub-rpms-template.sh

Along with normal aliPublish RPMs, allowing for multiple versions of the same
package to be installed at the same time, this feature enables the creation
of more standard RPMs, without the version name hardcoded in the package string.
Such RPMs are installable without specifying the version:
yum install alisw-dim
and updatable the same way.
All updatable RPMs get unpacked under the same prefix (as opposed to a different
prefix for each package). Modulefiles through the `aliswmod` command work
accordingly.

Add generation of "updatable" RPMs

---

list-branch-pr

The code was trying to get the /orgs/{org}/team URL
regardless of if a trusted team was provided on the command line.
Now it ensures a value was provided before doing so.

Fetch org teams only if trusted-team flag is provided

---

daily-aliphysics.sh
jenkins/daily-aliphysics

This allows to move entirely the "latest AliRoot version" configuration to alidist, via proper defaults. Jenkins configuration will not need any update anymore.

Use alidist defaults for Jenkins daily builds

---

publish/aliPublish

No network access should be performed at all when in test mode. This allows running `aliPublish` tests outside our internal clusters

aliPublish: do not use mesos-dns in test mode

---

daily-tags.sh

* Remove `grep -E '\s'` not supported on SLC5's `grep`...
* Add check to make sure `AUTOTAG_HASH` is never empty, to prevent turning
commands like `git push origin $AUTOTAG_BRANCH:...` into accidental deletions

Fix HEAD lookup in daily tag script

---

cvmfs/alienv
publish/aliPublish-nightlies.conf
publish/test-nightlies.yaml

Such updates are backwards-compatible and do not break current production
`alienv` usage on the Grid

CVMFS alienv updates for O2 deployment

---

publish/aliPublish-nightlies.conf

Allows posting _to_ alice-o2-software-support@cern.ch by using the same _from_ address.

Fix nightlies sender email

---

publish/publish-data.sh

Abort implies mount operations, and we must ensure we are not under the CVMFS tree while aborting, otherwise the abort operation itself (which is supposed to happen quite rarely and to recover automatically) will fail.

Publisher: move outside of CVMFS when aborting

---

ci/README.md
ci/run-continuous-builder.sh

This is the script (with proper documentation) allowing to run the `continuous-builder.sh` command as it is on macOS without Aurora. The script is accompanied by proper run documentation.

Add macOS continuous builder scripts

---

ci/continuous-builder.sh
ci/run-continuous-builder.sh

* Add support for INFLUXDB_WRITE_URL
* Add support for `gtimeout` from Homebrew if `timeout` is n.a.

Fix CI InfluxDB and timeout on macOS

---

ci/continuous-builder.sh
list-branch-pr

This changes two things in continuous builder to make coverage
report also for branches.
First of all commits on branches in the main repository are always
considered "trusted" since someone must have merged them before.
Secondly, in the case of branches the PR number is actually the branch
name, so we do not pass that to codecov, since it seems to be confused
by it and drops the report.

Make coverage work for branches

---

ci/continuous-builder.sh
ci/run-continuous-builder.sh
report-pr-errors

* Clean build directories to avoid space usage explosion and inconsistent build results due to previous artifacts
* Clean dead Git references growing indefinitetly
* Add ability to force-test only given commits for debug

Improve stability of continuous integration

---

.travis.yml
cvmfs/alienv
cvmfs/test-alienv.sh

Improve alienv for AliEn integration

---

publish/publish-data.sh

`.cvmfsdirtab` is configured to create a catalog in each data directory, however
prior to publishing the base diff directory already contains the catalog file
placeholder, and the new one does not contain it yet, causing `diff` to report
the two directories to be different when in fact they are not

Exclude .cvmfscatalog from OADB dir comparison

---

publish/aliPublish
publish/aliPublish-nightlies.conf
publish/aliPublish-rpms.conf
publish/aliPublish.conf

This helps preventing publishing too many packages at the same time due to a simple configuration mistake. It also assumes that "everything was fine" during the last X days and there is no "hole" (missing packages) to fill, speeding up publishing considerably.
Configure it to a reasonable value: by default the old behaviour is unchanged (never exclude anything)

Publish: exclude packages older than X days

---

publish/aliPublish

Publisher needs to run on SLC6 nodes with a native Python 2.6. That version has `datetime` lacking `total_seconds()`, therefore we work around it.

Publish: fix for total_seconds in Python 2.6

---

ci/continuous-builder.sh
ci/run-continuous-builder.sh

Same as #589 but extents the scope to Aurora builders as well. A parallel
update is being pushed to the Aurora configuration and builders will be rolling
updated

CI: use aliBuild from pip in Aurora builders

---

ci/run-continuous-builder.sh
daq-da-rpms.sh

Complements #589 and #590. Fix:
* aliBuild + alienv from PATH in DA RPMs
* aliBuild + aliDoctor from PATH in manual CI runner (does not affect prod)

Fix alienv + aliDoctor from PATH too

---

publish/get-and-run.sh
publish/publish-cert.sh

Perform daily synchronization (after 5am) of the CERN IT-managed CA certificates
from `/etc/grid-security` to CVMFS.
* Additional certificates (non-IT-managed) are possible (for instance, AliEn CA)
and they will be synced from a separate directory
* Resiliency: the script does the sync continuously, after 5am during the day,
until it converges; retries are automatic upon failures
* As per policy, CRLs are not copied and erased on the destination

Sync Grid CA certificates to CVMFS

---

publish/publish-cert.sh

Zero-padded numbers are interpreted as octal by bash

CVMFS: do not zero-pad hours in certificate pub

---

daq-da-rpms.sh

`info` accidentally pruned in #598

Fix yum info typo in DAQ DA RPMs

---

ci/conf/alidist_o2-0.sh
ci/conf/alidist_o2-1.sh
ci/conf/alidist_o2.sh
ci/conf/o2-0.sh
ci/conf/o2-1.sh
ci/continuous-builder.sh
ci/run-continuous-builder.sh
mesos-dns-lookup
report-pr-errors
setup.py

* Add new O2 macOS builders: 2 for O2, 2 for O2Suite on alidist
* Support fetching of extra repositories along with the PR one and alidist
* Document `force-hashes` for debugging purposes
* Create separate logfiles for each PR/branch build, identified by PR/branch
name and timestamp
* Fix `glob()` behaviour in `report-pr-errors`, now catches both `*latest*` and
`*latest` (it was the case with `AliRoot-guntest`)
* Make warm up phase faster (no sleep)
* Add builtin support for Mesos DNS API (no need to change the host DNSes)
* Allow support for virtualenv (do not use `pip install --user` in that case)
See also O2-436

Improve reliability of the CI

---

report-pr-errors

As far as I can tell all the text logs available from the PR checks (in ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2 at least) are duplicated (because of "latest" links).
This should fix it.

Fix to avoid duplicate logs.

---

build-rpm-sync.sh

Avoids false positives. Triggers only on final completion

Fix RPM checking: do not check for `staging` RPMs

---

mesos-dns-lookup

* Error handling in case of bad arguments.
* Provide sensible defaults for MESOS_DNS variable.
* In case we find no result with the web API, return the provided
argument as fallback as the local DNS might still provide a viable
answer (e.g. if a local caching dnsmasq is provided).

mesos-dns-lookup: improve reliability

---

publish/run-all-rpms.sh

* This is required so that we can run the script with a different user and still be able to rsync files to destination with the proper ownership.
* Also slightly change check for environment variables so that we do not leak secrets to the logs.

RPM publishing: force chown of destination files & reduce chances of leaking secrets to log

---

publish/aliPublish-rpms.conf
publish/pub-rpms-template.sh
publish/test/test-repo.sh

* Add test package to those being published.
* Exclude compile_commands.json from RPMS, so that they do not
conflict in the updatable RPMS.

RPM publishing: address O2-852, O2-437, O2-849 and O2-853

---

alibot_helpers/github_utilities.py
list-branch-pr

* Drafts pull request are now ignored by default.
* Simplify logic to trust collaborators.
* Trust members (since they were added by some owner).
* Trust owners.

list-branch-pr: improve reporting logic (O2-1202)

---

ci/continuous-builder.sh

Rather than testing all the PRs before we start reporting results,
we test one and then we move to the "hot" mode.

ci/continuous-builder.sh: ONESHOT only test a single PR

---

ci/continuous-builder.sh

Plan is to deprecate and remove our own InfluxDB / Grafana instance
as we do not have manpower to maintain it.

Report PR timing to Google Analytics

---

ci/build-helpers.sh

First PR always starts from scratch, so it biases the results.

Report timing for the first PR in a separate category

---

daily-tags.sh
jenkins/daily-tags
setup.py

* Run with -x -e always. Drop printouts which are really debug statements
* Always assume a slug is given in the form `<org>/<repo>[@<branch>]`
* Use GIT_DIR rather than pushd when possible
* Do not rely on pipefail. Rework code which assumes it
* Use `grep -m1` option in place of `| head -n1`
* Use `awk END{...}` rather than `tail -n 1`
* Always use `--fetch-tags`
* Allow `REMOTE_STORE` to be set from the outside

Simplify daily builds script

---

alidist-override-tags
setup.py

Add a separate script to override the versions of packages
which we want to build.

alidist-override-tags: initial import

---

ci/conf/aliroot_aliroot-guntest_next-root6_macos.sh

In #746 macOS builders have been renamed.
After the renaming of the macOS builders, the ALIROOT builder keeps asking for a mandatory passing build by `/build/Aliroot/macos` which has been decommissioned, despite the new builder being in place.
The quickest solution seems to be to go back to the old name until we find out why it keeps asking for the the old builder.

(O2-1532) Revert renaming for ALIROOT macOS CI

---

publish/aliPublish.conf

This way we can build O2 / AliPhysics using a preinstalled CVMFS area.

Publish build_requires

---

publish/pub-file-template.sh

Now that we install build_requires, it's not fatal to not
have an environment file.

publisher: do not fail on missing module file

---

publish/aliPublish.conf

This PR should enable publishing of individual O2 builds with JAliEn-ROOT and TNetXNG file access backend to be tested at GSI. There might be more GSI specific test builds in the future so `_GSI` tag should be ok for this purpose.
cc @costing

Whitelist O2 GSI specific test builds

---

publish/pub-rpms-template.sh

Those are not overlapping and are needed to allow compiling from a pre-existing installation.

Delete conflicting files only for Updatable RPMS

---

list-branch-pr

By taking only the first hex digit of the commit SHA, only the first 16 workers
would actually process PRs. Turning the entire SHA into a "bigint" is very fast
and allows a huge number of simultaneous workers.

Allow more than 16 simultaneous workers

---

list-branch-pr

Don't fall back to other PRs, to avoid slowing down the build.
Without this change, the CI builder will wait for some minutes and test
already-tested PRs again before moving on to the next repo, which may have
untested PRs.

Only print untested PRs

---

list-branch-pr

Printing the approving reviewers on stdout here confuses the CI build script.
This PR gets rid of the print statement and simplifies the logic above.

Fix extraneous output from list-branch-pr

---

ci/build-helpers.sh
ci/build-loop.sh
ci/continuous-builder.sh
list-branch-pr

This PR should be merged together with the corresponding GitLab merge request.
This PR changes the CI build script to poll multiple repositories for PRs to build, instead of just one.
Repo-specific configuration is kept in `ci/repo-config/<docker-image>/*.env` files; the worker clones the ali-bot repository to get those files.

Unified CI builder

---

ci/repo-config/mesosci/slc8/o2-alidist.env

This un-special-cases it -- it needs a special alibuild version, but that can be done with the new CI builder.

Add alidist-centos8 CI job

---

ci/build-helpers.sh
ci/build-loop.sh
ci/continuous-builder.sh
list-branch-pr

This PR:
- exec's continuous-builder.sh instead of looping, so updates to that script are picked up
- sleeps if there are no PRs to build in any repository, so GitHub API calls aren't used up too quickly
- gets rid of a pointless loop in list-branch-pr
- uses a common GitHub API cache for list-branch-pr

Improvements to CI builder

---

list-branch-pr
report-pr-errors

This shares the cache between difference repositories in the unified CI builder (saving API requests), but doesn't rely on a specific directory structure (and therefore supports local testing more easily).

Store GitHub cache in $HOME

---

report-pr-errors

This makes debugging easier, as GitHub will show the hostname of the machine building the current PR; it also makes diagnosis of stuck builders a little easier.

Add a message to GitHub status when build has started

---

ci/build-helpers.sh

These variables should never be empty, so provide defaults in case something goes wrong.
I've seen some errors in the logs where `TIMEOUT` somehow becomes unset occasionally.

Provide defaults for TIMEOUT and LONG_TIMEOUT

---

ci/continuous-builder.sh

This avoids pointless reinstalls and fixes an issue with pip trying to install incompatible versions of PyGithub.

Only upgrade ali-bot and alidist if needed

---

report-pr-errors

The docker containers are set to UTC anyway, and converting times to Europe/Zurich would probably require the pytz library, which is more faff.

Show timezone in pending build status

---

ci/build-loop.sh

This stops rebuilds from setting the status from success/failure to pending, which is confusing (see AliceO2Group/AliceO2#4641).

Only set pending status on first build

---

report-pr-errors

This extracts the important messages out of the large log files, so users can find the more easily. The HTML file is uploaded to S3 alongside the full log file, and links to the latter so both are accessible. The GitHub status will link to the HTML file directly.
Untested so far; I'll work out how to do that sensibly tomorrow.

Extract error messages into separate HTML file

---

report-pr-errors

Don't include the alternative last-N-lines in the HTML in case no errors are found in a specific log, which can overwrite real errors from other logs.

Improve error list

---

ci/build-helpers.sh
ci/continuous-builder.sh

- `RECHECK_PRS` is not needed any more
- `reset_git_repository` needs `TIMEOUT` but it was only set in the build subshell

Fix environment variable scoping

---

repo-s3-mirror

This updates repo-s3-mirror to the rclone command that currently runs on Aurora, and adds support for translating symlinks into a format S3 understands.

Add symlink support to repo-s3-mirror

---

repo-s3-mirror

Bucket, prefix and repo can be overridden using command-line variables. If those are not given, the script falls back to the BUCKET, PREFIX and REPO environment variables; if those are empty, default values are supplied in the script.

Make options to repo-s3-mirror configurable

---

report-pr-errors

`grep` exits with an error if nothing is found, so this doesn't apply to those commands, but `sed` needs this extra check.

Don't print file names of logs where no messages are found.

---

repo-s3-mirror

This makes find read the link target directly, which is hopefully faster than using readlink. The script is now designed to be run without `set -x` (which gives far too much output).

Speed up repo-s3-upload

---

ci/build-helpers.sh

We only need to check up to one directory level up, so avoid checking for config/ directories in unrelated places on the system. This patch reduces the number of log messages a bit, as well.
The patch also gets rid of the JOBS variable, which should be set in the per-repo .env files. A global override doesn't really make sense as it needs to be tweaked per-repo anyway.

Clean up config/ handling

---

report-pr-errors

Under memory pressure, the build can fail when a compiler process is killed. This patch adds a message to the HTML log to that effect.

Show message in HTML log if compiler is killed

---

ci/build-helpers.sh
ci/continuous-builder.sh

With this patch, the ali-bot and alibuild versions to install can be controlled on a per-worker basis. This makes it easier to test patches to those on a single worker before deploying.

Make testing different ali-bot and alibuild versions easier

---

ci/build-helpers.sh

It can use these directly, so we avoid having to specify them in a config file.

Pass S3 credentials to aliBuild

---

ci/continuous-builder.sh

The Linux docker containers also have screen installed; we don't want to use it there though.

Run under screen only in MacOS

---

ci/build-helpers.sh
ci/continuous-builder.sh

`export -f` doesn't seem to have worked for passing the functions on.

Move timeout functions to build-helpers.sh

---

ci/build-helpers.sh

According to <https://alisw.github.io/infrastructure-macos>, we use `pip3` on MacOS. The `pip` binary does the right thing on Linux and MacOS in this case, selecting the right version.

Don't hardcode pip version

---

ci/build-loop.sh

Make it optional in the regex.

We don't include the leading thermos- when passing MESOS_EXECUTOR_ID

---

ci/build-loop.sh

Just give up and source the .env file to get all the variables right.

Fix queue messages for CI workers

---

ci/build-loop.sh

Remove extraneous `build/` and `prod/` from host ID.
Also, "Build queued" → "Queued".

Abbreviate pending message

---

ci/build-helpers.sh
ci/build-loop.sh
ci/continuous-builder.sh

These are left-over workarounds from the MacOS builder that don't apply any more.

Remove old workarounds

---

report-pr-errors

Remove the o2checkcode log from the general "errors and warnings" output, as it contains false positives and the important errors are already reproduced in the o2checkcode section.

Don't duplicate errors from o2checkcode

---

ci/build-helpers.sh
ci/build-loop.sh
ci/continuous-builder.sh
report-pr-errors

Remove unneeded global variables, workarounds for old versions of aliBuild, and make the code a bit more maintainable.

Remove obsolete workarounds in CI builder

---

report-pr-errors

Add a rule to `report-pr-errors` to find CMake errors and warnings and add them to the HTML log.

Extract errors from CMake

---

repo-s3-mirror

- fix a potential logic error (using `%P` in find)
- there's no need to get `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, as the
rclone config already contains those credentials (they used to be for `s3cmd`)
- avoid printing an error message from find when `$symlink_tree` doesn't exist
- add lots of comments to explain what's going on

Improve and document repo-s3-mirror

---

bulk-change-pr-status
setup.py

This script changes PR statuses in bulk for the given repos and checks, e.g. from error to pending. Helpful for undoing the damage of broken CI builders.

Add bulk PR-marking script

---

ci/build-loop.sh

In the previous reversion, I re-added the `NO_ASSUME_CONSISTENT_EXTERNALS` vars but missed the code that used them.

Revert to old build identifiers in CI

---

list-branch-pr

This processes whole .env files at a time, instead of line-by-line.
Note that it doesn't parse files perfectly! A command with an argument containing `=` would cause that argument to be parsed as an assignment. For example, `echo foo=bar` would parse as an ignored token `echo` and an assignment `foo=bar`. (This might be useful with export statements, actually.) As .env files are supposed to be simple key-value stores anyway, we can ignore this problem for now.
(Most of the diff is due to an indentation change caused by the removal of the for loop.)

Fix spurious shlex error

---

repo-s3-mirror

If a high-level directory is changed, this change means it won't be copied in its entirety, but only those subdirectories of it that have changed.

repo-s3-upload: Make symlink search more efficient

---

ci/build-loop.sh

On the Macs, `MESOS_EXECUTOR_ID` isn't defined, so we fall back to the hostname. They don't understand `--fqdn`, though. `-f` is more compatible.

Use MacOS-compatible hostname invocation

---

daily-tags.sh

When another package is successfully tagged using `daily-tags.sh`, also tag the corresponding commit of alidist that was used.

Tag alidist with other daily tags

---

report-pr-errors

They don't always have a call stack attached. They always end in an empty line, but sometimes contain empty lines so this will truncate some error messages (but at least not flood the output in case of a missing call stack).

Fix CMake error extraction

---

ci/build-loop.sh

The outer subshell is around the while loop, not inside it, so we need another to contain the `cd ..`.

Fix queue statuses: need an extra subshell

---

ci/build-loop.sh

Missing a `!`.
PR builds were not uploaded to S3 as aliBuild automatically disables a remote write store for dev packages.

Fix logic error in remote store assignment

---

ci/continuous-builder.sh

We need this as we `cd` into repo-specific directories inside the loop. The automatic subshell around the loop doesn't get us back to the sandbox directory after each iteration.
This means we don't query for pending PRs after each iteration but only when done iterating, as intended. This means new incoming PRs don't displace old untested ones in the queue.

Run CI iterations in a subshell

---

publish/pub-rpms-template.sh

If the modulefile is missing, we fix it, rather than spamming people.

Drop check for modulefile

---

report-pr-errors

- handle more cases, including:
- gmake-style errors and warnings
- "fatal errors" (which occur in failed unit test results)
- treat all `***` messages as errors
- errors like `Error in <TSystem::ExpandFileName>: input: ..., output: ...`, as seen in [this QC build](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/QualityControl/553/db2a782cf5da374327438663d86a08bb8fbe9ebd/build_QualityControl_o2-dataflow/fullLog.txt)
- separate warnings from errors, as warnings tend to be more
false-positive-heavy
- ignore CMake warnings entirely, as they are almost never useful

Improve HTML log

---

ci/build-loop.sh

The Macs are set to CET, not UTC by default, so use `date -u` as we assume UTC now.

Always report UTC build time

---

report-pr-errors

Don't include "Warning: Unused direct dependencies" in the HTML output log. These are apparently false positives and can't be turned off at the build level.

Silence false positive linker warnings

---

report-pr-errors

This replaces grepping for `***` with a more precise search for make/gmake errors (e.g. when a compiler is killed), a type of cmake error, and failed tests, which is what that pattern is for. This means disabled tests don't show up in the HTML error log any more.

Reduce false positives in log output

---

report-pr-errors

Should be disabled anyway, so remove the clause that looks for it.
Previously, we found the following messages by looking for lines of 79 asterisks:
```
*******************************************************************************
*----------------------------------- ERROR -----------------------------------*
* The variable 'CMAKE_CXX_COMPILER' should only be set by the cmake toolchain,
* either by calling 'cmake -DCMAKE_CXX_COMPILER="/opt/rocm/hip/bin/hipcc"' or
* set in a toolchain file and added with 
* 'cmake -DCMAKE_TOOLCHAIN_FILE=<toolchain-file>'.
*-----------------------------------------------------------------------------*
*******************************************************************************
```

Ignore CMAKE_CXX_COMPILER warning in HTML log

---

list-branch-pr

For new (yellow) PRs, older ones have been in the queue longer and should thus be built first in the interest of fairness.
For previously tested (red and green) PRs, we take a single random PR to test, so the sorting has no effect.
This modifies the check slightly so that if there are no green or yellow PRs, a red one is always built. Previously, there was a 30% chance of falling through the check for red PRs, even if there were no green ones, leading to a 10-minute sleep.

Minor improvements to list-branch-pr

---

.github/workflows/pr-check.yml

The publish step gets skipped if nothing changed any relevant files, so the error didn't crop up until now.

Install required python modules in workflow

---

.github/workflows/pr-check.yml

python-ldap requires libldap2-dev; using other packages' pre-built binaries requires python3-wheel.

Add missing system requirements for pip dependencies

---

daily-tags.sh

The git installed on the Jenkins machine only understands plain `--porcelain`.

Fix git invocation

---

jenkins/daily-tags

An update to binutils seems to break the GCC-Toolchain build. It works in a clean slc6-builder container, so remove the yum update.
The yum installs seem to break the autotools build, so remove them.

Remove yum update/yum install from SLC6 Jenkins builds

---

publish/pub-rpms-template.sh

Sometimes files which are removed in the updateable RPMs are also removed in the non-updateable ones. If this is the case, we should at least have them present.

Verify interference of updateable RPMS wrt non-updateable ones

---

daily-tags.sh

On CentOS 8, plain `pip` doesn't exist. Also, `python` is `python3` there, so a fallback to `pip3` makes sense.

daily-tags: fall back to pip3 if pip not found

---

publish/pub-rpms-template.sh

Unfortunately, the old RPM pickup new `aliswmod`, I thought all deps are fixed, but `aliswmod` is the exception. Let's revert it for the moment and find out how to do it in a clean way.

Revert dropping aliswmod #903 #944

---

jenkins/daily-tags

This should solve two problems where the builder runs out of disk space and where some git repos get corrupted and can't be updated from the server.
The diff makes more sense when you ignore whitespace changes.

Clean up after daily build; retry build twice

---

build-any-ib.sh

Due to complaints about builds failing due to a lack of RAM.
The fullCI builds have the same amount of RAM as the Jenkins builders, and only have `--jobs 9`.

Build with 9 jobs in build-any-ib

---

publish/aliPublish-rpms-cc8.conf

The running CC7 publisher won't pick this config file up automatically (and neither will the CC8 publisher), so it's safe to merge.
This file publishes O2 vYY.WW, and emails are enabled!

Publish RPMs on CC8

---

ci/build-loop.sh

Regular packages' build logs are normally deleted right after the build by aliBuild, but this means that e.g. the o2checkcode logs aren't kept for the fullCI builds.
This change leaves some leftovers in INSTALLROOT and BUILD that `aliBuild clean` won't clean up.

Don't auto-cleanup build logs in CI

---

report-pr-errors

This means we can use negative lookaheads (so we don't need `grep -P`, which causes problems). As a bonus, we don't have to shell out to grep/sed, and we also avoid the spurious "error parsing log file" messages in the CI log on aurora when grep doesn't find an error message in some of the logs.
I've tested the new `grepall` function on its own, and it works fine.

Do log grepping internally

---

report-pr-errors

Adds a "O2 full system test" section to the HTML log, which shows up if either of these types of problem was detected:
- `task timeout reached`
- `Detected critical problem in logfile`

Extract full-system-test-specific log messages

---

publish/check-for-published-rpm.sh

This script is intended for use in Jenkins. It creates a canary file that the RPM publisher removes when done, then checks if an RPM was created as expected, tries to install it, and reports success if this check is OK.
Untested so far.

After build, wait for RPMs to be published

---

publish/aliPublishS3

- use boto3 to fetch packages on S3 (HTTPS API doesn't return the whole list)
- file modification times are now ignored -- this was a failsafe before
- S3's "fake" symlinks are handled properly
This command uses a slightly different config format; the existing slc7-specific config files are kept. #969 uses the new format for the CC8-specific file.
Supersedes #971.

Add separate aliPublishS3 command to publish from S3

---

publish/run-all-rpms.sh

The new script also pulls changes to ali-bot on every iteration, and loops faster (sleeping only a minute between iterations).
This is to simplify the aurora service definition.

Update publishing script with setup and canary files

---

ci/continuous-builder.sh

The largest allowable limit seems to be 10240 on alibuildmac00. The others have a maximum limit of 24576, and on Linux the maximum limit is even higher. This patch doesn't change the ulimit if it is already large enough, as the O2 full system test on Linux needs a very high ulimit.

Only increase ulimit if needed

---

report-pr-errors

Detect more classes or errors:
- `fatal:` from git
- `ninja: build stopped:` e.g. when compiler is killed due to a segfault or OOM under ninja
- `[ERROR]`: various errors in O2 tests

Detect git, ninja and O2 test errors in logs

---

publish/run-all-rpms.sh

We aren't producing updatable RPMs at the moment, so no need to sync the directory.

Don't sync UpdRPMS for CC7 and CC8

---

publish/run-all-rpms.sh

This is so that it doesn't keep creating docker containers.

Convert run-all-rpms.sh to long-running job

---

publish/check-for-published-rpm.sh

This adds an explanatory message to the script that waits for an RPM to be published. If case no new RPM is found, this may not indicate a failure of aliPublish, but the previous step might just not have produced a new tarball to publish.

Mark build unstable if no new RPM is found

---

daily-tags.sh
jenkins/daily-tags

This fixes a bug where the date rolls over while waiting for PRs, leading to an incorrectly named tag.

Parse AUTOTAG_PATTERN before waiting for PRs

---

daily-tags.sh

Builders are runnning out of memory, again.

Reduce Jenkins jobs to 8

---

report-pr-errors

Find timed-out unit tests as well, not just failed ones.
A double `%` was included previously because a `grep` command was constructed using `%`-formatting. This isn't the case any more, so the duplicate `%%` means we accidentally ignore the unit test summary line.

Improve unit test result parsing

---

report-pr-errors

Seen e.g. in <https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/5745/eb46138d1ea6e0b9d651f18a92c39ad6700cf902/build_O2_fullCI/fullLog.txt>.

Add [FATAL] messages (from O2 system test) to HTML log

---

ci/build-helpers.sh
ci/build-loop.sh
ci/continuous-builder.sh

This git clone sometimes gets stuck, so clone it with a timeout instead.
This patch moves the shared cloning logic into reset_git_repository and calls it when needed -- this simplifies the separate logic for dev packages and ali-bot.

Add timeout to dev packages' git clone in CI

---

report-pr-errors

This means that any build error is likely to be at the end of the log, as expected.
Tested and working.

Sort build logs in chronological order, oldest first

---

ci/continuous-builder.sh

`WORKER_INDEX` and `WORKERS_POOL_SIZE` aren't set when `list-branch-pr` runs because they're only updated in a subshell. This PR also updates them when we fetch PRs.

Get overrides before fetching PRs to build

---

jenkins/daily-tags

These are already set in the Docker container, but those settings apparently aren't applied in our build containers.

Manually set required build vars for CC8 O2 builds

---

update-symlink-manifests

The script reads pseudo-symlinks for all packages in `TARS` on S3, and makes a single file per package, which aliBuild can fetch to speed up cloning the remote store.
This script uses threading to speed up fetching many small files from S3.

Add script that creates symlink manifests

---

.github/workflows/pr-check.yml

`ubuntu-latest` is now Ubuntu 20.04, which doesn't provide a package for `pip2`. Using Ubuntu 18.04, we can continue to test using `python3` and `python2`.

Use Ubuntu 18.04 for PR checker

---

report-pr-errors

- move SSH command to summary table
- add a note about `alientest*` machines
- remove extraneous link to full log

Improve HTML build log

---

ci/build-loop.sh
ci/continuous-builder.sh

I suspect that something inside build-helpers is reading its stdin. This causes the remaining contents of `$HASHES` to be discarded, so the outer loop doesn't process the last PRs in its queue.
I also patched the other places where we use `echo | while read`, just in case.

Fix CI skipping PRs in the queue

---

ci/repo-config/mesosci/cs8/o2-alidist-dataflow.env

This is the only check to be newly added (instead of migrated from slc8), so use this for testing.

Add alidist o2-dataflow check on CentOS Stream 8

---

report-pr-errors

These context lines are just noise, and hide the important information.

Omit confusing context lines from HTML log for unit test results

---

bulk-change-pr-status

This makes it easier to only reset checks from before a particular change was introduced.

bulk-change-pr-status: Allow filtering by date

---

ci/build-helpers.sh
report-pr-errors

Except when building alidist, in which case include all logs.
This cuts down on the number of useless messages in the HTML log.
Errors and other messages are still shown from all logs in all cases.
Untested so far -- if it's OK, I can deploy it to one builder first, before merging.

Only include warnings from logs for main package in HTML log

---

publish/run-all-rpms.sh

Boto3 is dropping support for python2, so we should move aliPublish over to python3. As a stopgap to make the publisher work for now, install concurrent.futures ourselves.

Publisher: Install concurrent.futures for boto3

---

publish/aliPublish.conf

Matched value includes revision, so we need to account for it.

Correct regex to match O2Physics tags

---

bulk-change-pr-status

Add a feature to bulk-change-pr-status that allows changing the status of a commit back to what it was before the latest status was set. This is better for cleaning up after broken builders, as if things were green before, they can go back to that, while PRs that didn't have a status before things were broken will be yellow. This means that fixed builders have potentially much less of a queue to rebuild.
A special case is that if the previous status is red, then we force-reset it to pending because the logs from the earlier red status will have been overwritten by now.

bulk-change-pr-status feature: Reset to previous status

---

jenkins/daily-tags

Currently, the Jenkins daily-tags script takes up a slot on an slc7-light node for the full duration of the build, even though that slot is only needed for the initial step of waiting for PRs to be merged (and most daily builds don't even use that step).
With this patch, that slot is only used as long as it is needed, and is freed when the real build begins on another node.
The diff contains mostly whitespace changes.

daily-tags: Don't take up an slc7-light node when it's not needed

---

publish/get-and-run.sh

aliPublish is run using python3, so use pip3 to install.

Install dependencies for aliPublish

---

publish/get-and-run.sh

Apparently using requirements.txt forces full installation, including the [services] stuff.

Only install minimal dependencies for the publisher

---

daily-tags.sh
jenkins/daily-tags

Now that O2Physics is a separate repo, it and O2 shouldn't take as much memory to compile.

Make daily-tags compilation jobs configurable

---

rpms/o2-prereq.spec

This is already embedded in the slc7-builder and it is required to be able to install and run aliBuild using python3 as it contains python36-requests and python36-pyyaml

Require EPEL release for python36

---

.github/workflows/o2-full-deps.yml

This will allow us to drop python2 builds on CC7.

Use python3 for aliBuild also on cc7

---

daily-tags.sh
jenkins/daily-tags

Allow tagging multiple packages with the same tag in daily-tags.sh.
This is needed to tag O2, then tag and build O2Physics with the same tag immediately afterwards.

Parallel tagging of related packages

---

jenkins/daily-tags

On Ubuntu, we want to use pip (which points to the correct version) instead of pip3.

Make daily-tags Jenkins script Ubuntu-compatible

---

daily-tags.sh

If the defaults file doesn't contain a `tag:` or a `version:` override for the packages we're building, it is not changed. If it contains either, the specified override(s) are forced to the tag/version we're building.
Untested, but it's a fairly simple change.

daily tags: Don't set tag/version overrides if not needed

---

daily-tags.sh

In that case, we don't push a new tag for it, but still edit its `tag:`/`version:` keys (for the alidist tag).
This should fix O2PDPSuite builds, as that recipe doesn't have a `source:` key.

Fix daily-tags.sh when a package has no git repo

---

publish/aliPublishS3
publish/run-all-rpms.sh

With this patch, aliPublishS3 won't need a full local copy of the entire repo any more. Instead, it will merge new RPMs into the S3 repo directly, and upload the RPMs directly as well (so the `rclone sync` step isn't needed for aliPublishS3 any more).
Publishing tested and working using the `el8.test` architecture.

Run aliPublishS3 off S3 repository only

---

ci/repo-config/macos/alibuildmac03/qualitycontrol-o2.env
ci/repo-config/mesosdaq/cs8/qualitycontrol-dataflow.env
ci/repo-config/mesosdaq/cs8/qualitycontrol.env
ci/repo-config/mesosdaq/slc7/qualitycontrol-dataflow.env
ci/repo-config/mesosdaq/slc7/qualitycontrol.env

These were accidentally disabled.
This also enables O2 unit tests (because both use the same variable), and because we check against O2@dev, we can't always reuse the nightly prebuilt tarballs, so checks will take a little longer.
Cc: @knopers8 @Barthelemy

Reenable unit tests for QualityControl

---

ci/repo-config/mesosdaq/slc7/infologger-dataflow.env
ci/repo-config/mesosdaq/slc7/monitoring-dataflow.env

As for QC. Also enables O2 tests, but in these cases we should be able to reuse nightly tarballs for O2.

Reenable unit tests in Infologger and Monitoring

---

rpms/o2-prereq-cc8.spec

While not strictly required for aliBuild, it looks like the are now for O2 software.

Require rsync and GLEW devel

---

build-any-ib.sh
daily-tags.sh
jenkins/daily-tags

This causes errors when installing a different version of alibuild and then trying to run it.

Don't use pip install --ignore-installed

---

publish/run-all-rpms.sh

This makes the Mattermost notification work on architectures where we only publish to S3, not locally.
Tested and working using the `el8test.x86_64` architecture.

Look for newly published RPMs on S3 instead of locally

---

build-any-ib.sh

The default of 9 jobs is still left over from before the O2/O2Physics split. 16 should be fine now.

Use 16 jobs by default in build-any-ib

---

ci/repo-config/macos/alibuildmac04/alidist-o2.env

Add a check for O2, alidist, QC and O2Physics.
Draft until the builder is fully deployed.
Cc: @MichaelLettrich

Add CI checks on new M1 Mac

---

report-pr-errors

If a unit tests triggers an assertion error somewhere, CTest will report `Subprocess aborted***Exception` instead of `***Failed`.

Handle "***Exception" messages in unit tests logs

---

publish/aliPublishS3

alibuild uploads the tarball last, so if it doesn't exist yet, the list of symlinks in dist/ that we got from S3 is likely incomplete. Therefore, skip publishing the package for now.
Untested.

aliPublishS3: Check for tarball before creating RPM

---

report-pr-errors

Previously, only specific compiler errors were recognised, so the script posted a useless comment including only unrelated lines of some log file. Instead, search for all error messages (but not warnings) that we know about, so the comment is more useful.

Include all known error messages in posted comment

---

alibot_helpers/utilities.py
ci-status-overview
list-branch-pr
requirements.txt
setup.py

The script queries recent pull requests' CI statuses for each known check and displays the results in a concise and colourful table for easy analysis.
Also extract `.env` file parsing into a library function as it's used by both `list-branch-pr` and the new script.
The new script uses GraphQL, so add a dependency.

Add script to show an overview of recent PRs

---

report-pr-errors

Also, remove `^fatal:` messages -- these are from git, and are mostly false positives.

Recognise coloured error messages

---

ci/repo-config/mesosci/slc7-o2physics/o2physics.env

Already enabled on Mac.
This enables `-Werror`.

Enable ALIBUILD_O2_TESTS in O2Physics Linux CI

---

ci/repo-config/macos/DEFAULTS.env
ci/repo-config/macos/alibuildmac04/DEFAULTS.env

There's nothing useful on it at the moment anyway, and it prevents us from using
system packages.
Cc: @MichaelLettrich

Don't use remote store for Mac CI

---

ci/process-pull-request-http.py

In some cases, the "list" of approvers can be a boolean instead of a set. That
case wasn't handled by my previous change.

Fix PR processing: handle case where rule is a bool

---

alibot_helpers/github_utilities.py
ci/build-helpers.sh
ci/build-loop.sh
set-github-status

When we're automatically rebuilding a check, it would be helpful for users to have feedback about this, so change the existing status's message (keeping the red/green status and results URL intact).
This requires an extra option to set-github-status to keep the URL intact, which is added by this commit as well.
Untested so far, so I've made this a draft PR for now.

Update check message when rebuilding

---

ci-status-overview
list-branch-pr
requirements.txt
setup.py

This uses much fewer GitHub API requests than the script relying on the REST API, so it should help us stay within quota.
Python-gql 3.1.0 has been released, so we don't need to keep pinning a prerelease version any more.
Still needs testing, so draft for now.

Change list-branch-pr to use GraphQL

---

ci/build-loop.sh

For some reason, on some machines, /etc/httpd/*.pem are created as empty directories.

Ignore directories when searching for hostkey/cert

---

ci/build-helpers.sh
ci/build-loop.sh

After every build, delete builds and installations of development packages that haven't been touched in two days. This should hopefully keep disk usage under control.
A better solution would probably be to monitor the absolute disk usage of the CI builder and delete as many old builds as we have to to stay within our limit, but that would be much more complicated, and counting our own disk usage would take a long time.
Also, monitor the time taken by the cleanup process. For this purpose, factor out a function for pushing to InfluxDB, which could be used to push additional metrics in the future.
Untested so far.

Clean up unused builds after 2 days

---

ci/repo-config/DEFAULTS.env

Fixed issue with leftover go installs, plus a few more.

Use alibuild 1.11.4

---

ci/build-loop.sh
ci/cleanup.py
ci/continuous-builder.sh
setup.py

When disk space runs low, clean up more old builds, so that we always have 100 GiB available before every build.
This replaces the old bash-based cleanup procedure with a more full-featured Python script.
Metrics are tracked per-check and pushed to InfluxDB.

Smarter cleanup for CI

---

ci/repo-config/DEFAULTS.env
ci/repo-config/mesosci/slc7-aliphysics/aliphysics-release.env
ci/repo-config/mesosci/slc7/aliroot-alidist.env
ci/repo-config/mesosci/slc7/aliroot.env

Move remaining AliRoot ROOT5 checks to ROOT6 and delete the ROOT5 AliPhysics check, where we already have a ROOT6 one.

Remove ROOT5 CI checks

---

publish/aliPublishS3

Fetch directory contents individually from S3, instead of fetching the whole file tree in advance and caching it. This is much quicker if only publishing a few packages.

Speed-up aliPublishS3

---

publish/aliPublish.conf

This is needed to run analysis trains using AliPhysics versions compiled on slc7.

Publish jemalloc on slc7 as well

---

ci/continuous-builder.sh
ci/repo-config/DEFAULTS.env

If builds complete too fast, throttle them (so that there are at least 2 minutes, configurable, between the start of each build), so that we don't burn through our GitHub API request quota too quickly.

Avoid rebuilding so fast we run out of GitHub API requests

---

publish/aliPublish
publish/aliPublishS3

Changing `dict.get(_, [])` to `dict.setdefault(_, [])` ensures the cached value is actually assigned in the dictionary and isn't immediately dropped.
Tested and working with the AliEn publisher. With this patch, the time it takes to run `get-and-run.sh` with nothing to publish goes from 3 min to 2 min.
Some things, like O2-customization, still get needlessly reinstalled even with this patch applied because they don't appear in the output of `alien -exec packman list -all -force`. I don't know why.

Fix caching of installed AliEn packages in aliPublish and aliPublishS3

---

daily-tags.sh

Add the `CREATE_ALIDIST_PULL_REQUEST` variable. Unless it is set to "true", changes to alidist will only be pushed to the requested tag.

Daily tags: only create/update alidist PR if requested

---

ci/continuous-builder.sh

Occasionally, `list-branch-pr` just seems to hang for a while. Timeout in that case, so we don't block builds forever.

Timeout if `list-branch-pr` takes too long

---

.github/workflows/c++-code-formatting.yml

This check is used in O2 and O2Physics.
In CMake files and in macros, check for the same copyright notice as in "regular" C++ files.

Check for the correct copyright notice in CMake files

---

list-branch-pr

For some permissions-related variables (such as `TRUST_COLLABORATORS`), this fixes buggy behaviour where the most-permissive value encountered would be applied, even if overridden in a more-specific `.env` file.
As far as I can tell, this problem only occurred with the Mac CI check in AliRoot, where the check would run for anyone who had authored commits in the AliRoot repo, instead of only after a `+1` comment.

Fix overloading of some variables in `.env` files for CI

---

publish/pub-alien-template.sh

We currently have every automatic publishing run fail because the script can't find `$TORDIR`. This probably shouldn't be an error.

Don't publish AliEn torrents

---

ci/continuous-builder.sh

This fixes a mistake in the invocation of the cleanup script, leading it to look for files to clean up in the wrong places. This only occurred on builders where `ALIBOT_CONFIG_SUFFIX` was set (those split off from the "main" builders for their respective platforms), i.e. the O2Physics and AliPhysics builders.

Fix CI cleanup

---

ci/build-loop.sh

This should allow Nomad to clean up processes and track CPU use accurately.
Draft as I haven't tested it yet.

Run CI builds inside our Nomad-assigned cgroup

---

publish/aliPublish
publish/aliPublish.conf

Remove Mesos-specific DNS feature from aliPublish

---

.github/workflows/c++-code-formatting.yml

The old way of setting output data, using `::set-output ...`, is deprecated and will be removed by GitHub eventually. For details see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This commit replaces the old commands with the new way of doing things, i.e. using the `$GITHUB_OUTPUT` file.

Use new GitHub environment file

---

.github/workflows/c++-code-formatting.yml

The `ubuntu-latest` GitHub runner was updated to Ubuntu 22.04, which only preinstalls clang-format 12 to 14, so update to clang-format 14.
To make sure clang-format keeps working during the 8-week transition period where `ubuntu-latest` may randomly refer to 20.04 or 22.04, pin `ubuntu-22.04`.
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

Update clang format to track GitHub runner

---

publish/aliPublish.conf
publish/test.yaml

Publish O2sim, HEPscore-CCDB and dependencies for slc7_aarch64 on CVMFS.

Publish aarch64 packages

---

ci/build-loop.sh
report-pr-errors

...and add it to the HTML log for CI. This should reduce the number of cases where we produce an empty log significantly.
This uses the functionality added in https://github.com/alisw/alibuild/pull/784.

Pick up information on failed git commands from aliBuild

---

cvmfs/alienv

This is required for aarch64 support.
The hardcoded x86_64 string was not changed in `load_alien_if_missing`, which should only run on `el5` -- and we don't have any `el5` ARM machines.

Support non-x86_64 architectures in alienv

---

ci/build-helpers.sh
ci/build-loop.sh

This metric would be useful to see which commits on the dev/master branch introduce regressions.

Track number of commits on the base branch in CI

---

report-pr-errors

The o2checkcode log can contain spurious errors, so handle it specially when constructing the GitHub comment that the CI leaves in pull requests.
Cc: @davidrohr

Fix handling of o2checkcode errors in CI comment

---

publish/aliPublish-rpms-cc8.conf
publish/test-rpms-cc8.yaml

I think this is causing the repeated publishing failures for the `bookkeeping-api` version `bookkeeping@0.49.1-1`.

Exclude bookkeeping-api versions with @ from RPM publishing

---

publish/aliPublish-rpms-cc8.conf
publish/test-rpms-cc8.yaml

The broken package from #1235 is still being published, as it's being pulled in by other packages. Exclude them, since there's no point in publishing them.

Exclude packages depending on broken bookkeeping version

---

publish/aliPublish
publish/aliPublishS3

If a package was completely missing from the output of `alien -exec packman list -all -force`, it was previously ignored completely (and always taken to be uninstalled). However, packman doesn't list defaults-release, UUID and O2-customization for some reason, causing aliPublish to keep republishing these.

Fix listing installed AliEn packages

---

ci/continuous-builder.sh

This patch allows using Docker containers hosted on registry.cern.ch for CI. It is also backward-compatible with docker.io containers (which are specified without a leading hostname).

Allow using registry.cern.ch containers in CI

---

setup.py

This is the same approach that alibuild already uses.
Recent pip versions have stopped accepting "LAST_TAG" as a valid version number. We used a constant "0.0.0" version as a stop-gap, but this still had problems -- pip didn't update the installed ali-bot version sometimes, since it assumed that the right version was already installed.
This new, proper versioning scheme encodes the commit number (and hash) in the autogenerated version number, so auto-updates (e.g. in CI) should work properly.
This will allow us to get rid of some hacky workarounds in the CI scripts as well.
Tested and working on CentOS 7 and above under Python 3.6+.

Use setuptools_scm for automatic versioning

---

ci/continuous-builder.sh

Once both alibuild and ali-bot use setuptools_scm versioning, we can remove these workarounds. This ought to make our venvs simpler and reduce failures from e.g. changing which repository to install from.
Depends on #1245 in ali-bot; alibuild already uses setuptools_scm.

Remove workarounds for invalid Python version numbers

---

.github/workflows/c++-code-formatting.yml

It would be less potentially confusing if we ran the same git-clang-format version in CI as people will run locally. Locally, we expect people to run git-clang-format in alienv, so they'll get the one installed with alidist, which is currently v15.
Clang-format v15 is not preinstalled in any GitHub runner images, so we have to explicitly install it, but we can also get rid of the "ubuntu-22.04" pinning.

Update clang-format to v15 to match alidist

---

publish/aliPublish-rpms-cc8test.conf
publish/aliPublish-s3-updatable-rpms.conf
publish/aliPublishS3
publish/pub-updatable-rpms-template.sh
publish/run-all-rpms.sh

This branch includes the changes to the CentOS 8 RPM publisher that I've been testing recently. Most importantly, this allows us to publish updatable RPMs for CentOS 8 (i.e. off S3).
At David's request, I also changed the updatable RPM publishing script to install stuff in package-specific (but not version-specific) subdirs, so e.g. O2 executables would go in `/opt/alisw/elX/O2/bin/`, instead of `/opt/alisw/el8/bin/`. Modulefiles still all go in `/opt/alisw/elX/etc/Modules/modulefiles/`.
Tested and working as far as I can tell, but comments/feedback would be appreciated.

Fix code paths for updatable RPMs

---

build-any-ib.sh

If the cloned ALIDIST_REPO isn't called "alidist", then subsequent steps fail to find it. Give it the right name.

Fix alidist directory name

---

ci/cleanup.py

Delete old nightlies for non-development packages as well, as they pile up and take up too much space otherwise.
Tested and working on a CI builder. Fine to merge after the weekend in my opinion.
Cc: @costing -- this should keep disk use under control a bit more.

Clean up old nightly tags in CI

---

.github/workflows/check-cvmfs.yml
cvmfs/alienv

Might be best to just use a wildcard. If you prefer explicitly listing version numbers instead, let me know @ktf.

Handle 2X.* versions of Ubuntu in alienv

---

cvmfs/alienv

Handle distro ID on RHEL 9

---

publish/aliPublishS3
publish/get-and-run.sh

This allows us to run the AliEn publisher elsewhere, e.g. through Nomad for better monitoring.
Draft and untested since the auth mechanism isn't implemented yet by @costing as far as I know.

Run AliEn publisher under Nomad using authenticated alimonitor API

---

publish/aliPublishS3

Change `aliPublishS3` for RPMs to download the latest package index file, and if it finds any uploaded `.rpm` files that are not in the index, download up to ~10GiB of them and add them to the index.
This will gradually rebuild the index to include all uploaded RPMs.
Also, backup old index files before replacing them (so we never catastropically lose the entire index), cleaning up index files that are older than a month.
Tested and working with the el8 RPM repo.

Gradually re-index RPMs if they are missing from the repo index

---

alibot_helpers/github_utilities.py
report-pr-errors
set-github-status
summary-pr-report
utils/bulk-change-pr-status

This makes all scripts using the GitHub REST API use the same cache file, hopefully reducing the number of API requests slightly overall, and leaving fewer cache files all over the disk.

Unify handling of GitHub cache file

---

ci/build-helpers.sh
ci/continuous-builder.sh
list-branch-pr

This should give a good approximation of the time a commit was submitted for testing. It still breaks down for draft PRs that are marked non-draft after a while.
Draft because it needs testing.

Track commit push time

---

pyproject.toml

ali-bot is not updated properly in CI when using `pyproject.toml` because `setuptools_scm`'s configuration is broken.
This fixes it and allows CI to auto-update ali-bot again.

Fix setuptools_scm versioning when using pyproject

---

ci/build-loop.sh

These are used by o2checkcode and O2DPG.

Make ALIBUILD_*_HASH variables available in build container

---

ci/repo-config/mesosci/slc7/o2-alibuild.env

This installs the alibuild version with changes proposed in the PR, then builds QC with that alibuild version to test it.
This is fine to run on the same build machines as other CI, since we isolate the Python environment in a venv and the next build will overwrite alibuild with its own version.

Build QC as CI for alibuild pull requests

---

list-branch-pr

People's first contributions to O2 are not tested automatically for security reasons. This often leads to confusion, so set a message on those commits to let people know that they need a PR approval.

Set a status message when commits are untrusted

---

.github/workflows/c++-code-formatting.yml

Both changes are pretty simple, so it seemed easier to bundle them into one PR.
See commits below for more details.
1. 'Annotate error messages with file/line number in output log': as requested by @davidrohr.
2. 'Remove unneeded "check passed" summaries': These only take up space on the summary page, and since GitHub only renders the first few step summaries, a few "check passed" summaries can mask errors further down the page.
Hide whitespace/indentation changes in the diff to make it even simpler.

Formatting workflow improvements

---

.github/workflows/c++-code-formatting.yml

The SHAs that GitHub provides might be outdated, so we'd see lots more changed files than are actually in the given PR.
By using the branch name (and fetching branches after cloning, for good measure), we should always get the latest commits in question.

Always use branches (not SHAs) for formatting workflow

---

build-any-ib.sh
daily-tags.sh

This will attach any given comment to the top-level package(s) to be built.

Allow users to specify build comments for Jenkins builds

---

.github/workflows/check-cvmfs.yml

That check was looking for some ancient, now-deleted AliPhysics nightly tags. Update it to use recent ones.

Fix "Check CVMFS scripts / alienv" check

---

.github/workflows/async-auto-label.yml
.github/workflows/async-list-label.yml

* add workflow that allows to add async-<name> labels by issuing a comment in a PR, e.g. ``` +async-label async-<name-add> !async-<name-remove> ... ``` Labels starting with a "!" shall be removed.
* add workflow that reminds developers to add async-<name> labels in case the development is needed for production software releases. A message is printed after the PR has been (re)opened

Add async-label functionality

---

cvmfs/alienv

If we're loading a symlink, the normal version detection won't work, so just check and we successfully loaded any version of the package on the right architecture.

Handle <package>/default symlinks in alienv

---

build-any-ib.sh

This brings build-any-ib.sh in line with what daily-tags.sh already does.

Use Python 3 by default, except on old platforms

---

ci/repo-config/mesosci/slc7-o2physics/o2dpg-sim-tests.env

Hopefully, this will help catch problems like https://its.cern.ch/jira/browse/O2-4706 earlier.

Run O2DPG sim tests when contents of DATA/ change

---

update-symlink-manifests

This should make publishing much faster, once publishers can start to use pre-built manifests to avoid having to walk the full dist tree on S3 themselves.
For now, nothing uses these new dist manifests yet; the next step would be to make `aliPublishS3` read them.

Extend symlink caching script to handle dist symlinks

---

ci/repo-config/DEFAULTS.env

Move CI to use aliBuild v1.17.0
- It should be much more performant
- Tested for over two weeks with the full-ci builds

Move CI to use aliBuild v1.17.0

---

publish/aliPublish.conf

For some reason to be understood, it gets added as a dependency to a lot of modulefiles

Publish ApMon for ARM

---

publish/aliPublish.conf

Publish build time dependencies
Apparently something (AliGenerators?) pulls them in as actual dependencies

Publish build time dependencies

---

.github/workflows/c++-code-formatting.yml

Users still often miss that a formatting PR has been made to fix their PR. Linking user's PR in the message of the formatting PR automatically makes the reference appear in the conversation of the original PR, which makes the formatting PR more visible to the user.

Show PR URL in the message of the formatting PR

---

requirements.txt

pip now complains when trying to install the old 1.45 version with:
```
Collecting PyGithub==1.45
Using cached PyGithub-1.45.tar.gz (113 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [11 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 14, in <module>
File "/Users/alibuild/venv/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
import setuptools.version
File "/Users/alibuild/venv/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
import pkg_resources
File "/Users/alibuild/venv/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2178, in <module> …
```

Update requirements.txt to PyGithub==1.46

---

publish/get-and-run.sh

Over the weekend, some "pip install" invocations took forever, for unknown reasons. Wrap the "pip install" invocation in a timeout, so that it is aborted and retried if it hangs.

Abort "pip install" in publisher if it takes too long

---

jenkins/daily-tags

Update pip before running the check for PRs
Needed on obsolete platforms

Update pip before running the check for PRs

---

ci/repo-config/DEFAULTS.env
ci/repo-config/mesosci/cs8/o2-dataflow.env

The previous git fix seems to be working properly, so we're bumping the
version for all builders #1347

Update alibuild to 1.17.6

---

daily-tags.sh
jenkins/daily-tags

This should make it easier to debug issues where pip and python are
mismatched (it can happen when manipulating $PYTHONUSERBASE)
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE

Verify that we're always using the pip matching our current python

---

.github/workflows/o2-full-deps.yml

This version has been available for a while and seems stable. The most
notable change is managing the git repos with --filter=tree:0, which
should mean a notably smaller sw/ folder size
Setting it to draft as centos7 is now EOL, so the action might fail when trying to deploy to those repos

Bump alibuild to 1.17.7 on centos&ubuntu repos

---

rpms/o2-prereq-el7.spec
rpms/o2-prereq-el8.spec
rpms/o2-prereq-el9.spec
rpms/o2-prereq-fedora.spec

Without readline-devel the shells built with alibuild are very annoying to use.
This would add it to both the builders and anyone building via [the official guide](https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-alma9.html)

Add readline-devel to alice-o2-full-deps

---

publish/aliPublish.conf

Install all build_requires on Alma9 as well

Install all build_requires on Alma9 as well

---

.github/workflows/o2-full-deps.yml

Bypasses the setuptools_scm `from __future__ import annotations` issue. 
We're not bumping it for all versions in case it brings other problems

Upgrade alibuild tag for old centOS versions

---

jenkins/daily-tags

Force PIP to use a mounted volume for unpacking
For some reason it considers the / overlay full, even if it's not.

Force PIP to use a mounted volume for unpacking

---

jenkins/daily-tags

Needed for Ubuntu 24.04, otherwise fails because of the new "externally managed envs" (https://peps.python.org/pep-0668/)
I can look into how to make it specific for Ubuntu 24.04 only if you'd rather not have this on all daily releases
Tagging @ktf

Create daily tags inside venv

---

metagit/__init__.py

This reverts commit 0c3ea99d8ed8ffcbf67b52d5642cfddc4fd0f211.
We still depend on MetaGit in some legacy jobs

Revert "Delete metagit directory (#1381)"

---

publish/aliPublishS3

Improve installation order
In case we need to split the packages to be installed, always keep
the toplevel packages last, so that we do not risk

Improve installation order

---

publish/aliPublishS3

List of packages is actually a dict

List of packages is actually a dict

---

.github/workflows/clean-pr-checks.yml
.github/workflows/o2-full-deps.yml
.github/workflows/pr-security-approval.yml

Recently removed from the docs as a supported distro
https://github.com/alice-doc/alice-analysis-tutorial/pull/168
The build on Ubuntu 18 is currently failing because of a pip issue anyway, it's probably not worth fixing it if we don't support it

Remove Ubuntu 18.04 from apt repository

---

analytics/report-analytics
ci/sync-mapusers.py
report-pr-errors

We don't use python2 anywhere anymore, and these imports are tough to
analize for LSP (694396ea0b923a52dab72fe3c643e634e4b44e41)

Remove python2 support in imports

---

.github/workflows/cacheo2package.yml

Triggers the build in Jenkins without going through our old kerberos setup. I'm
adding it here as it affects several repositories, but I wouldn't be opposed to
adding it to alidist/AliceO2/etc either
Requires adding several secrets to the Github Action runners before working,
currently named:
```
JENKINS_URL
SSO_AUTH_URL
SSO_JENKINS_API_CLIENT_ID
SSO_JENKINS_API_CLIENT_SECRET
SSO_JENKINS_API_TARGET_APP
```

Add CacheO2Package action

---

.github/workflows/o2-full-deps.yml

Fix the builds in Ubuntu PPA
The GPG changes are done to allow importing the key non-interactively
In order to work properly, the GPG key must be added to both https://keyserver.ubuntu.com/ and the Ubuntu PPA https://launchpad.net/ubuntu/+ppas

Fix GPG input

---

alibot_helpers/github_utilities.py
report-pr-errors

Should make it easier to debug in the future

Improve logging on GitHub API errors

---

daily-tags.sh

Temporary patch to keep the build names predictable. Ideally we wouldn't
need to specify the exact date of the build, but for now this patch
should at least keep it protected from daylight savings timezones
https://its.cern.ch/jira/browse/O2-5469
CC @ktf

[O2-5469] Migrate daily builds to UTC

---

ci/repo-config/DEFAULTS.env
ci/repo-config/macos/DEFAULTS.env

The tests for the new alibuild syntax on macOS seem to be successful, so I'm bumping all builders to the new version
If all https://github.com/alisw/alidist/pull/5660 Linux tests pass with this new version, I think it's okay to go ahead with bumping to alibuild@v1.17.12 on RPM/APT and merging that PR.
CC @ktf

Bump all CI builders to alibuild v1.17.12

---

.github/workflows/o2-full-deps.yml

Fixes the issue on build-o2-full-deps, it was indeed a problem with the
interactive use, like you said @ktf

Don't use tty in non interactive env

---

ci/repo-config/DEFAULTS.env
ci/repo-config/mesosci/slc9-o2physics/o2-o2dpg.env
ci/repo-config/mesosdaq/slc7/qualitycontrol-fullsystest.env

Some jobs have been crashing as they were running out of disk space
there
e.g. https://ali-ci.cern.ch/alice-build-logs/alisw/alidist/5660/f82c06050ddf1c0a1e3a55eed017af114b233139/build_O2_alidist-cs8/pretty.html
Follow up to https://github.com/AliceO2Group/O2Physics/pull/8343#issuecomment-2468079895

Increase Docker tmpfs size

---

.github/workflows/c++-code-formatting.yml

Should stop the CI from complaining about 3rd party headers not having the CERN copyright.
Look like it's been broken for a while, some older PRs have the same issue (e.g. https://github.com/AliceO2Group/AliceO2/pull/13490)
CC @ktf @ChSonnabend

Ignore 3rd party files when checking for copyright notice

---

ci/repo-config/DEFAULTS.env

Updating builders to latest aliBuild. The only relevant change for CI builders is https://github.com/alisw/alibuild/pull/884

Bump all CI builders to alibuild v1.17.13

---

publish/aliPublish-rpms-cc8.conf

From now nothing but whitelisted packages will be published, to avoid
ending up with a gigantic repository.

Change the logic for publishing releases

---

ci/run-http.sh

The process-pull-requests-http job is failing again when trying to authenticate
against GitLab. This PR makes it use the same credentials as the CI runners, so
they only have to be rotated in one place
Should fix the issues with AliPhysics PR jobs stuck in the "pending" state
CC @ktf

Centralize Gitlab credentials in Vault

---

.github/workflows/build-any-ib.yml
requirements.txt

**Not ready for merge, creating PR for testing**
This action will launch the build-any-ib job in Jenkins via SSO, the idea is to implement all needed workflows dependent on this one so we decouple as much as possible from Jenkins, to make it easier to migrate to nomad.
CC @ktf

WIP: Add build-any-ib GH action

---

.github/workflows/c++-code-formatting.yml

As reported by @davidrohr 
Should fix https://github.com/AliceO2Group/AliceO2/actions/runs/12818036733/job/35742588079?pr=13865

Don't require spaces in makefiles

---

.github/workflows/o2-full-deps.yml

Mantic has been deprecated and the mirrors are down, and centos 7 glibc
is too old for the new checkout action, so we'll have to live with the
warning for now

Fix o2-full-deps

---

jenkins/daily-tags

We've tried several workarounds to fix the issues with the venv, but
haven't managed. The install runs in a docker container anyway, so there
shouldn't be any problem with installing this way, and it will better
match the other architectures
CC @ktf

Fix ubuntu24 daily tags

---

daily-tags.sh
jenkins/daily-tags

Yet another attempt to fix Ubuntu24 installs. The whole daily tags setup could probably be simplified

Don't upgrade pip twice

---

.github/workflows/c++-code-formatting.yml

As reported by @davidrohr
https://github.com/AliceO2Group/AliceO2/pull/13999#issuecomment-2676244405

c++-code-formatting: Ignore 3rd party files when checking whitespace

---

.github/workflows/smoke-test.yml

Should prevent issues like https://github.com/alisw/ali-bot/pull/1490
Not testing Python 3.6 because it requires ubuntu20, and the runner image will be EOL next month

Verify if pip install fails on PRs

---

list-branch-pr

This reverts commit 0fb57da11fe3bdeb63926b9b5a753d3776d207e4.
It's bringing problems with out of sync dependencies

Revert "Don't run the new list-branch-pr system on Aliphysics (#1501)"

---

ci/repo-config/mesosci/slc7-aliphysics/aliphysics-root6.env

To try and fix the issue for the weekend, I'm updating only the Aliphysics
builder to the following patch:
```diff
diff --git a/list-branch-pr b/list-branch-pr
index 1117f702..860978fb 100755
--- a/list-branch-pr
+++ b/list-branch-pr
@@ -265,6 +265,12 @@ def main(args):
else:
org, _, repo_name = repo.repo_name.partition("/")
+                    
+                    # Skip processing for alisw/aliphysics repository
+                    if repo.repo_name.lower() == "alisw/aliphysics":
+                        print(f"Skipping ignored repository: {repo.repo_name}", file=sys.stderr)
+                        continue
+                        
repo_info = query_repo_info(session, org, repo_name,
repo.branch_ref,
args.show_base_branch)
```
It seems to affect other testers negatively somehow, I …

Don't run the new list-branch-pr system on AliPhysics

---

ci/repo-config/mesosci/slc7-aliphysics/aliphysics-root6.env

This reverts commit 351b864fc0dd9e93e0bdb7f6e1ed17cdafaec9b0.
This is still not desirable behaviour, not even in AliPhysics. The tester is no longer picking up PRs
The real problem needs further investigation, but this is definitely not the solution

Revert "Don't run the new list-branch-pr system on AliPhysics (#1505)"

---

cvmfs/alienv

This is a small change picked from #1445 to test whether #1459 is
properly creating the backups of the original alienv
CC @ktf

Fix shellcheck warning

---

publish/aliPublishS3

Reverts alisw/ali-bot#1459. This breaks because it fails to create the backup on a readonly volume.

Revert "Sync alienv to CVMFS automatically"

---

publish/aliPublishS3

This should fix the mismatch between # being correctly handled by boto3,
but not by a direct request via requests.

Make sure special characters are escaped when using requests

---

publish/aliPublish-rpms-cc9.conf

In this PR:
- I update the emails/owners of some components which are not following them anymore so that we are not missing any potential critical notifications. 
- If a tool had only one email person, I replaced with someone else from the same team.
- QCG tool was replaced entirely as it has not been part of an RPM or alidist recipe for a few years now.

Update notification lists with current users

---

.github/workflows/check-untested-packages.yml

The defaults are included in recipes indirectly so our ad-hoc logic for
detecting them as untested doesn't work

[O2-6297] Don't show defaults packages as untested
