.gitignore, run-docker-builder.sh
=> RunDocker: manually run builders

logstash/logstash.conf
Those are really referring to the previous line.
=> Do not catch warnings which start with "or" or "but"

es/build_summary.json
- More results
- Use non analysed fields for package name.
=> Improved summary query.

aliCvmfsPublish, aliCvmfsPublish.conf
=> Adjustment to new modulefiles path

aliPublish, aliPublish.conf
This simplifies dramatically the publication procedure.
=> Automatically follow dependencies while publishing

logstash/logstash.conf
Poll mesos master metrics and pushes results to both
elasticsearch and monalisa.
=> Support Mesos metrics

aliPublish.conf
Fixed wrong regexp in #75, sorry.
=> Really publish AliPhysics releases

logstash/logstash.conf
Gets metrics from marathon and pushes them to elasticsearch.
=> Monitor marathon

aliPublish
=> Programmatically test if a given pkg matches rules

build-any-ib.sh
=> Option to not use remote store

aliPublish, aliPublish.conf
Uses fpm for package creation. Dependencies are also handled.
=> Publisher: create RPMs and RPM repositories

cvmfs/alienv
=> alienv script updated to support CentOS/CC 7

build-any-ib.sh, config.yaml, schedule.py, test-any-ib.sh
This will allow us to run the same builds in coverage mode or using root6.
=> Add support for specifying different defaults

riemann.yml, riemann/config.rb, riemann/riemann.config, riemann/ws_config.json
Since all this is ALICE specific, I decided to move it here from
the alisw/docks repository. This also simplifies development, you just
need to do:
docker-compose -f riemann.yml up
to have a working rieman setup with our configuration.
=> Move riemann setup in ali-bot

publish/pub-alien-template.sh
Prevents problems with some SEs.
=> Select best AliEn SE for publishing to Packman

publish/pub-alien-template.sh
Added parameter that queries SEs for writing (default is for reading).
=> Improve best SE selection for AliEn publishing

jenkins/release-alibuild
This will build and upload the last tag of alisw/alibuild to PyPi.
=> Jenkins pipeline to release alibuild from a tag of alibuild

jenkins/deploy-cluster-updates
Run a number of ansible configurations one after the other to configure
build cluster.
=> Add Jenkins Pipeline to deploy Ansible updates

jenkins/generate-web-pages
- Use mirror for alisw.github.io
- Remove spurios quotes from warnings.json (sigh)
=> Make generate-web-pages more robust

jenkins/validation-pwg-emcal
Will probably need adjustments committing it here to start working on
the jenkins tests.
=> Initial commit of validation-pwg-emcal

cvmfs/alienv
=> Fix alienv error in g++ test program

cvmfs/alienv
=> Map Fedora 17 to 21 to RHEL in alienv

publish/.gitignore, publish/aliPublish, publish/aliPublish.conf, publish/get-and-run.sh, publish/pub-alien-template.sh, publish/pub-cvmfs-template.sh, publish/pub-rpms-template.sh
* Unnecessary HTTP requests are not performed any longer
* Enabled HTTP dethrottling and retries
* Optionally use insecure HTTPS connections for very special use cases
* All HTTP options implemented both in `requests` and in `curl` used in scripts
=> Improve publisher HTTP requests

publish/aliPublish, publish/get-and-run.sh
Lock automatically expires after `kill_after_s` seconds.
=> Add lock to prevent multiple concurrent instances

jenkins/deploy-mirror-updates
- Use native git checkout from pipeline
- Use ansible plugin
=> Improve deploy-mirror-updates

publish/aliPublish.conf
=> Remove POWHEG from publishing

jenkins/deploy-hlt-updates
Streamline inventory and parallelize deployment
=> Improve Ansible HLT updates

set-github-status
Simple utility to set github commit states
=> Add set-github-status

ci/continuous-builder.sh
- Add support for building generic packages
- Make checkout of packages as an external action
- Add support for defaults
- Set status for builds
- Make delay between builds configurable
- Correctly set errors
=> Improve ci/continuous-builder.sh

ci/continuous-builder.sh, list-branch-pr, report-pr-errors, set-github-status
- Can test PR and branches
- Reports PR errors as comments to the PR
- Reports errors in branches as issues and closes them
when the commit is outdated
- Highly reduce the amount of API calls required
=> Improve support for PR testing

publish/aliPublish
* Automatic retry three times
* Automatically include dependencies
=> aliPublish: more sensible defaults

cvmfs/README.md, publish/README.md, publish/aliPublish-example.conf
* aliPublish documentation
* CVMFS alienv documentation
* Simple aliPublish example configuration
=> Document setup of a CVMFS software namespace

check-open-pr.py, daily-aliphysics.sh, jenkins/daily-aliphysics
* Backwards compatible
* Wait for open pull requests before starting
* Jenkins pipeline
* Email notifications on failure
=> Add daily tags creation from GitHub

report-pr-errors
Do not expect line numbers together with the error, include some context.
=> Improve handling or error reports

ci/continuous-builder.sh, list-branch-pr
- Fix option name
- Allow usage via environment variables
=> Improve support for parallel builders

report-pr-errors
- Error messages on stderr
- Do not create a duplicate comment for the body of a PR.
- Refactor logic a bit
=> Cleanup report-pr-errors

.gitignore, README.rst, alibot_helpers/github_utilities.py, analytics/report-analytics, analytics/report-metric-monalisa, ci/continuous-builder.sh, list-branch-pr, monitor-github-api-monalisa.sh, report-pr-errors, set-github-status, setup.py, test/test_githubCachedRequest.py, test/test_githubUtilities.py
This is a squashed summary of what had to be done / fixed in order to get PR checking to the level it was when the Github migration was announced to the public.
=> Sprint to get PR checking in production

publish/aliPublish-nightlies.conf, publish/test-nightlies.yaml
=> Publish test AliGenerators on nightlies

alibot_helpers/github_utilities.py, summary-pr-report
- Print PRs with errors since more than 1h
- Print PRs with pending status since more than 1h
=> Add helper script to print open loops

publish/aliPublish-rpms.conf
* Publish flpproto RPMs
* Add @awegrzyn to RPM notifications
=> Add RPM generation for flpproto

publish/pub-alien-template.sh
* Get the first best storage elements (not just one)
* Try them in random order until a good one is found
This fix works around storage failures not detected by the MonaLisa health
check.
=> Add storage fallback on AliEn publisher

check-daily-slack.py
* Start checking after 4pm
* Check every 5 minutes: notify immediately if tag is OK (i.e. both on CVMFS and
AliEn)
* After 5.30pm send a message every 15 minutes if tag is not OK
=> Add Slack notificator for AliPhysics dailies

ci/continuous-builder.sh
* Support `du` and `gdu` (on macOS with Homebrew)
* Fix repos update when pull caused an unwanted merge
* Fetch origin before resetting to an origin branch
=> Improve continuous builder Git and macOS support

cvmfs/README.md, cvmfs/alienv
* Enable RedHat 7 among the list of preferred platforms
* Optionally override default CVMFS dir using ALIENV_CVMFSDIR
=> alienv: add el7 and optionally override CVMFS dir

publish/aliPublish-rpms.conf
=> Add Configuration-Benchmark to RPMs

.travis.yml
* Run tests only for things that changed
* Restore tests for `aliPublish` (previously ran on-premises)
=> Improve Travis CI scripts

publish/aliPublish-nightlies.conf, publish/test-nightlies.yaml
=> Re-add O2 CC7 builds

ci/sync-egroups.py
=> Add utility to query CERN egroups interactively

ci/continuous-builder.sh
Adds current ali-bot version, uptime and pull request processing time. Also adds
support for `--fetch-repos` in aliBuild if possible, see alisw/alibuild#511
=> Improve monitoring in continuous builder

alibot_helpers/github_utilities.py, alibot_helpers/utilities.py, report-pr-errors
Move to_unicode to a generic place while fixing the bug.
=> Fix unicode issue

check-daily-slack.py
Note: done to work around broken CVMFS monitor webservice at cernvm-monitor.cern.ch during Christmas break. Do not merge yet.
=> Use POSIX check as option to CVMFS checker

check-daily-slack.py
A file is touched every 60 seconds. Check last modified date via health check:
```
[[ $(( $(date --utc +%s) - $(stat -c%Y /tmp/check-daily-slack-health) )) < 100 ]]
```
=> Add health check to daily builds checker

build-any-ib.sh, daily-tags.sh, daq-da-rpms.sh
* GitHub slugs in build-any-ib
* `--fetch-repos` where appropriate
=> Improve Jenkins builds

publish/aliPublish, publish/aliPublish.conf, publish/get-and-run.sh, publish/test.yaml
This fixes the issues with the notification emails for invalid packages
=> Work around AliEn Packman problem

report-pr-errors
Use the correct URL to send the PATCH request to set issue state to
closed.
=> Fix automatic issue closing

cvmfs-mon/cvmfs-mon.yml
ASGC is disabled, one admin still wants to get notifications for the site anyways
=> Modify CVMFS ASGC contact persons

cvmfs/alienv
* Add `MODULES_USE_COMPAT_VERSION` in case system's modulecmd is too recent
* Add `$moduleenv` where missing
=> Add CVMFS alienv support for latest Ubuntu/Debian

publish/aliPublish-nightlies.conf, publish/test-nightlies.yaml
=> Exclude O2 nightly 20180425

publish/aliPublish-rpms.conf
=> Generate RPMs for Control-OCCPlugin

publish/aliPublish-rpms.conf
=> Sync RPM installation instructions with doc

repo-cleanup/.gitignore, repo-cleanup/README.md, repo-cleanup/gen-repo-report.sh, repo-cleanup/repo-cleanup.py, repo-cleanup/repo-cleanup.yml
Uses configurable policies, removes dependencies based on reference counting
=> Add aliBuild tarballs repository cleanup script

publish/publish-cert.sh
=> Fix CVMFS certs syncing granularity

ci/continuous-builder.sh
=> Use distinct build names across different CI jobs

publish/get-and-run.sh
As experienced in ALIROOT-7988
=> Add notifications for OADB publishing errors

publish/pub-rpms-template.sh
See QC-104 and jordansissel/fpm#1385
=> RPM generation: rename files with "bad" characters

ci/continuous-builder.sh, report-pr-errors
This happens through the Details button
=> Report CI logs on success too (O2-499)

publish/aliPublish.conf
* Avoid spamming Dario & Miguel on errors.
* Do not publish GLFW-3.3-090b16bfae-1.slc7_x86-64.tar.gz as it lacks modulefile.
=> Cleanup publishing

publish/pub-rpms-template.sh
We put it in aliswmod RPM since that's always required.
=> Provide env for updatable RPMs [O2-1027]

ci/continuous-builder.sh
As we want to move away from a single repository to S3,
I am removing all the non essential parts which still use
our own repository. This also avoids leaking the AWS_ACCESS_KEY_ID
to the logs.
=> continuous-builder.sh: cleanup use of repo.marathon.mesos

publish/aliPublish.conf
Ciao @ktf ,
maybe I managed, can you please check? I also updated the G4 regexp to be more flexible, even if I imagine that the dependencies of published packages are automatically published as well.
Let me know!
Cheers,
Max
=> Add the support to custom G4 builds

ci/continuous-builder.sh
@ktf : I think this will enable the --always-prefer-system on GPU, but not 100% sure :)
=> Build GPU CI with --always-prefer-system

build-any-ib.sh
* Less gymnastic with alibuild installation
* Avoid filling the out of bound "/build" folder, now that we
use static workers.
=> Simplify build-any-ib

ci/build-loop.sh
git update-ref does not support / never supported wildcards apparently
=> Properly clean stale PR tags

cvmfs-mon/cvmfs-mon.py, cvmfs-mon/cvmfs-mon.yml
CVMFS monitor service API has changed. Need to change
ALICE cvmfs monitoring script to stay compatible.
=> cvmfs-monitor: follow up on cvmfs monitor API change

ci/build-loop.sh, ci/run-continuous-builder.sh
=> Do not use MIRROR on macOS

ci/build-loop.sh
Sorry, this got lost when I manually squashed commits for #817.
=> Actually set pending status when build has started

ci/continuous-builder.sh
Pip apparently gets stuck sometimes when cloning the required git repos. In that case, time out and try again later.
=> Timeout when pip gets stuck

report-pr-errors
=> Show Mesos ID, not hostname, in pending message

ci/build-helpers.sh, ci/build-loop.sh, ci/continuous-builder.sh
Use the correct PR_REPO, as other queued PRs might be in different repos.
=> Fix queue status assignment

ci/build-loop.sh
Not sure why this was there in the first place. Errors should always go to the commit that was tested; `PR_REPO` and `PR_HASH` are always set, so no need for a fallback. Setting the `HEAD` of alidist to pending on every random build messes up PRs to that repo.
=> Don't report errors to alidist

ci/continuous-builder.sh
To avoid losing git credentials.
=> Keep initial HOME

ci/continuous-builder.sh
Source, then check whether variables are defined.
=> Fix order of operations

report-pr-errors
As seen in <https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/4767/233e2d32c23ca2b87eb13b5c21b3e09f11dd52d1/build_O2_o2/fullLog.txt>.
=> Handle compiler segfault messages

ci/repo-config/mesosci/ubuntu2004/o2-alidist.env
This sets `INSTALL_ALIBUILD=alisw/alibuild@S3-upload` so that we use alisw/alibuild#634 for now.
=> Add job for Ubuntu builder

.github/workflows/o2-full-deps.yml
I've created the secret already.
Currently set to upload to `rpms3:alibuild-repo/RPMS/o2-full-deps_x86-64/`.
=> Upload O2 repo to S3

ci/repo-config/mesosci/ubuntu1804/o2-alidist.env
I forgot to do this in the last PR, sorry.
=> Rename the Ubuntu 18.04 check to match

repo-cleanup/gen-repo-report.sh
The while loop handles spaces in filenames fine (but only breaks for newlines in filenames).
=> Use whitespace-hardened loop in gen-repo-report.sh

ci/build-loop.sh
This is set in some .env files but not exported.
=> Export ALIBUILD_O2_TESTS

report-pr-errors
- link back to built PR and commit
- show `aurora task ssh` command to log in to builder
- add info about host and aurora command to HTML log
- implement log writer in Python for portability
=> Improve build logs

ci/build-loop.sh
Seems like some of the queue position reports were broken as the .env files couldn't be found here.
=> Run source_env_files from sandbox dir

ci/continuous-builder.sh
Remove `force-hashes` when the PRs/branches in it were successfully built so the builders don't keep rebuilding the same ones indefinitely.
=> Improve force-hashes handling

daily-tags.sh
If the metadata YAML was changed in the appropriate `defaults-*.sh`, commit it and tag that commit.
Also preserve the non-metadata part of the script (this usually contains some explanatory comments).
As yet untested.
=> Commit and tag with changed version

ci/repo-config/mesosci/ubuntu1804/o2-alidist.env
The S3-upload branch is merged into master.
=> Use alibuild@master on Ubuntu builder

daily-tags.sh
=> Revert "Use tag, not branch, for daily releases"

.github/workflows/pr-check.yml
This is so we can see the diff from base to head.
=> Checkout whole repo for workflow

ci/build-loop.sh
So that we actually have better chances of reading the full
host spec.
=> Shorter build message

.github/workflows/pr-check.yml
I forgot that commands don't run as root by default.
=> Workflow: run apt under sudo

.github/workflows/pr-check.yml
=> Workflow: install libsasl

publish/aliPublish-rpms.conf
Publish the same things on CC8 as on CC7.
=> Publish RPMs on CentOS 8

publish/pub-rpms-template.sh
Since the revert did not work, let's try to fix it properly.
=> Revert "Revert dropping aliswmod #903 #944"

publish/aliPublish-rpms.conf, publish/pub-rpms-template.sh
We do not have an aliswmod binary anymore.
=> Do not create /bin for aliswmod

publish/pub-rpms-template.sh
=> Fix relocation of RPMS

ci/continuous-builder.sh
Git seems to need this for fetching large repos.
=> Increase ulimit on MacOS

publish/check-for-published-rpm.sh
`yum --assumeno` exits with an error, even if the transaction would have succeeded. The test mode is more comprehensive and has the correct exit code.
=> Use yum's test mode to install generated RPMs

ci/build-loop.sh
The trick with printf means read sometimes ignores the last line. Revert back to the old behaviour.
=> Fix development package fetching

build-any-ib.sh, daily-tags.sh, jenkins/daily-tags
In daily-tags and build-any-ib.
=> Allow configuring Python version

ci/build-loop.sh
This is less confusing than UTC.
=> Use CERN-local time zone for status message

alibot_helpers/github_utilities.py, bulk-change-pr-status
See individual commits.
The diff contains a block with only indentation changed.
=> Improvements to bulk-change-pr-status

publish/aliPublishS3, publish/run-all-rpms.sh
Tested and working for the el8 publisher.
=> Move to python3 for aliPublishS3

publish/aliPublish, publish/run-all-rpms.sh
Tested, working and already deployed for rpm_creation_el7.x86_64, but until this is merged, changes to `aliPublish-rpms.conf` on ali-bot's master branch won't be picked up by the job.
=> Run aliPublish with python3 as well

publish/run-all-rpms.sh
=> Post to Mattermost when new RPMs are published

publish/aliPublishS3, publish/run-all-rpms.sh
=> Revert "Run aliPublishS3 off S3 repository only"

publish/aliPublish.conf
`monalisa.sh` recipe in `alidist` will follow shortly.
=> Adding MonALISA entry for automatic publishing to CVMFS

daily-tags.sh
The FLP suite needs special handling, so add a variable (which can be used when scheduling a build in Jenkins), which is substituted for the current FLP suite version.
=> Add "FLPSUITE_LATEST" variable to ALIDIST_SLUG for daily tags

build-any-ib.sh
Same as for daily builds. Needed for CacheO2Packages job.
=> Use S3 remote store by default on slc8 and Ubuntu

ci/repo-config/DEFAULTS.env
Tested on cs8 builders and working fine.
=> Bump alibuild to v1.9.4

publish/aliPublish.conf
=> Revert "Publish FOCAL on slc7 as well"

publish/aliPublish.conf
=> Publish HEPscore-CCDB

ci/process-pull-request-http.py
E.g. if `@oadb` is allowed access to `OADB/`, then give them access to `OADB/PWGLF/` as well, even if the latter directory is covered by another rule.
The point about `num_approve` not being handled entirely correctly may be moot, as I can't find any config actually using that setting.
@ktf, @pzhristov: do you think this implementation satisfies the requirements to allow access to subdirs?
For example, the new implementation would newly allow access to:
- `OADB/{PHOS,PWG,PWGCF,PWGDQ,PWGGA,PWGHF,EMCAL,PWGPP,PWGUD}/` to `@oadb`
- `PWGCF/FEMTOSCOPY/{FemtoDream,macros}/` to `@alice-svn-pwgcf`
- `PWGPP/{ITS,benchmark,EMCAL}/` to `@alice-svn-pwgpp` and similar for other `PW*` top-level dirs
- everything to `@aliroot-git-admins`
- and more
Is this OK?
=> Give anyone with parent directory rights subdir rights as well

ci/build-loop.sh
Green checks will very likely cause a very fast build (as we'll have the build results cached, probably), which would use up our GitHub API request quota too quickly.
=> Don't update status for rechecks when green

daily-tags.sh
On Mondays, fetch the latest available tag; else, build against the installed version.
Cc: @davidrohr
=> Fix FLP suite version used in daily tags

daily-tags.sh, jenkins/daily-tags
This is a draft of the reworked implementation, as requested by @ktf. This also requires changes to aliBuild.
- allow templating in AUTOTAG_PATTERN (date formatting is done afterwards)
- allow overriding specific packages' tags
Cc: @davidrohr
=> Implement required changes for O2PDPSuite release process

ci/repo-config/mesosdaq/slc7/qualitycontrol-fullsystest.env
Also run the O2DPG full system test against QC's master branch.
Cc: @davidrohr @Barthelemy
=> Add QualityControl full system test

ci/repo-config/mesosci/slc7/o2-o2dpg.env, ci/repo-config/mesosdaq/slc7/qualitycontrol-fullsystest.env
=> Use 8G /dev/shm for O2-full-system-test checks

ci/build-loop.sh, ci/continuous-builder.sh, report-pr-errors
=> Change user-facing messages from Aurora to Nomad

ci/continuous-builder.sh
This won't prevent us from running out directly, but will allow us to spot when we start running out early in future.
=> Monitor GitHub API quota usage

build-any-ib.sh, build-package, build-rpm-sync.sh, daily-tags.sh, daq-da-rpms.sh, report-pr-errors
=> Use "real" hostname for repo machine

ci/build-loop.sh
The idea is to use them to select which checks to run.
=> Expose CI_NAME and CHECK_NAME

publish/aliPublish.conf
now moved to the aliPublish-noarch.conf
=> Drop AliDPG publishing

ci/build-helpers.sh
Push a metric to InfluxDB if a command takes longer than its timeout, so we can see if there are issues.
=> Monitor timeout overruns in CI

ci/repo-config/DEFAULTS.env
https://github.com/alisw/alibuild/releases/tag/v1.13.0
=> Upgrade aliBuild to v1.13.1 in CI

.github/workflows/c++-code-formatting.yml
Related PR in alidist: https://github.com/alisw/alidist/pull/4791
=> Sync clang-format version with the alidist recipe

ci/repo-config/mesosci/slc7-o2physics/o2dpg-sim-tests.env
Run the CI when things change in RelVal/ sub-directory
=> Forsee CI on RelVal

build-any-ib.sh, build-package, build-rpm-sync.sh, daily-tags.sh, daq-da-rpms.sh
The rsync repo is obsolete and everything should upload directly to S3 instead.
=> Change the default remote store to S3

publish/cache-ccdb.py
This stops the script from publishing too many transactions per day.
=> Abort empty CVMFS transactions

pyproject.toml
Apparently this is now required to be able to do pip install from git
=> Add pyproject

publish/README.md, publish/aliPublish-noarch.conf, publish/aliPublish-rpms-cc8.conf, publish/aliPublish-s3-updatable-rpms.conf
Say where to look for logs in each case.
=> Improve publisher error messages

publish/aliPublishS3
This should make debugging publisher delays much easier.
=> Log time of messages for publisher

.github/workflows/o2-full-deps.yml
=> Package aliBuild for Mantic

rpms/o2-prereq-el9.spec
Make Alma9 RPM spec platform agnostic
=> Make Alma9 RPM spec platform agnostic

.github/workflows/o2-full-deps.yml
More work to make workflows architecture independent
=> More work to make workflows architecture independent

publish/aliPublish.conf
Prepare to publish aarch64 on ALMA9
=> Prepare to publish aarch64 on ALMA9

ci/build-helpers.sh
Avoid leaking secrets when running in debug mode
=> Avoid leaking secrets when running in debug mode

publish/aliPublish.conf
=> More dependencies to install

publish/aliPublish.conf
=> Publish IgProf also for slc8

cleanup/cleanup-rules.yaml
Do not aggressively cleanup slc9
=> Do not aggressively cleanup slc9

rpms/o2-prereq-el9.spec, rpms/o2-prereq-fedora.spec
O2-5010: Use mariadb rather than mysql
=> O2-5010: Use mariadb rather than mysql

daily-tags.sh
=> Upgrade pip before using it

jenkins/daily-tags
Upgrade pip as requested by centos8
=> Upgrade pip as requested by centos8

ci/repo-config/mesosci/cs8/o2-dataflow.env
The last PR had a wrong alibuild version, apologies
=> Use temporary alibuild version for debugging

publish/aliPublishS3
Add timeout to publishing on AliEn
=> Add timeout to publishing on AliEn

jenkins/daily-tags
Accidentally committed without the ;;
=> Fix syntax for case

daily-tags.sh, jenkins/daily-tags
Should fix the issue with the corrupted venv in the jenkins builder
=> Use newer version of pip

build-any-ib.sh
Handle recent breaking changes in upstream pip
Drop support for python2, while we are at it.
=> Handle recent breaking changes in upstream pip

ci/build-loop.sh
=> Workaround cgroupsv2

ci/run-http.sh
Also removing old artifact from mesos
=> Upgrade pip before running the task

jenkins/daily-tags
=> Wait for PRs on slc9 nodes

ci/repo-config/DEFAULTS.env
Bump the builders to latest release
Follow up to https://github.com/alisw/alidist/pull/5439#issuecomment-2273064395
=> CI: Bump aliBuild version for builders

ci/continuous-builder.sh
Properly pass down aliBuild/alidist/ali-bot env variables for logging
Should fix #1359 when running in CI
=> Export variables for current version running in CI

daily-tags.sh
Removing old code. I added the : to keep it consistent with 2628efa4
=> Simplify REMOTE_STORE logic

.github/workflows/o2-full-deps.yml
Should be merged before https://github.com/alisw/alidist/pull/5660
=> Bump RPM and APT repositories to AliBuild v1.17.12

.github/workflows/c++-code-formatting.yml, .github/workflows/o2-full-deps.yml
=> Fix actions/checkout bump to right version

ci/repo-config/mesosci/slc9-gpu/o2-fullci-alidist.env, ci/repo-config/mesosci/slc9-gpu/o2-fullci.env
=> Create parallel FullCI testers in slc9

ci/repo-config/mesosci/slc9-gpu/o2-fullci-alidist.env, ci/repo-config/mesosci/slc9-gpu/o2-fullci.env
This reverts commit deedaae279371d1dcb3b258a32c83c48f1a16c82.
Issue should be fixed with https://github.com/alisw/docks/pull/278
CC @ktf @davidrohr
=> Enable slc9 fullCI again

jenkins/daily-tags
Prevents getting broken Python symlink inside docker
Should fix current dailies
CC @ktf
=> Fix venv in ubuntu24

.github/workflows/c++-code-formatting.yml
Follow up to https://github.com/alisw/ali-bot/pull/1454#discussion_r1920315466
=> Also check whitespace in .py and .sh files

pyproject.toml, requirements.txt, setup.py
This should finally fix the issues with conflicting deps...
CC @ktf
=> Fix dependencies

publish/aliPublish.conf
=> Publish test build for TTree reader plugin

publish/aliPublish-rpms-cc9.conf
As requested by @ehellbar
CC @ktf
=> Publish el9 RPMs too

jenkins/daily-tags
Without this, it crashes when trying to self upgrade pip
=> Fix Ubuntu24 again

alibot_helpers/github_utilities.py
This happens often in AliPhysics
We should probably reduce the number of updates to the commits somehow
at some point
=> Improve error message

pyproject.toml, setup.py
=> Clean up pyproject

.github/workflows/smoke-test.yml
Should make sure the dependencies are compatible between packages
=> Also install aliBuild on smoke test

pyproject.toml, requirements.txt, setup.py
This reverts commit 9571b39cc5f1b3c5dd2bc9e186b829e6d2a9d75e.
=> Revert "Remove old installation methods (#1506)"

publish/aliPublish.conf
=> Publish 2.X JAliEn versions

rpms/o2-prereq-el9.spec
=> Add rdma-core to o2-full-deps

ci/missing-persons.py, ci/process-pull-request-http.py, ci/sync-egroups.py, ci/sync-mapusers.py, cvmfs-mon/cvmfs-mon.py, metagit/__init__.py
Unused imports, cleanup comparisons, etc
=> Fix linter issues: Imports

ci/repo-config/mesosci/slc9-gpu/DEFAULTS.env
=> slc9-gpu: Bump aliBuild to v.1.17.18

pyproject.toml, setup.py
Workaround until https://github.com/alisw/alibuild/pull/921 is merged
=> Fix aliBuild installation

alibot_helpers/github_utilities.py
Includes prefer def over lambda, unused variables, unused f strings
=> Fix linter issues: Unused f strings

alibot_helpers/github_utilities.py, ci-status-overview, ci/check-open-pr, ci/missing-persons.py, ci/sync-egroups.py, ci/sync-mapusers.py, publish/aliUnpublish, report-pr-errors, set-github-status, utils/bulk-change-pr-status
=> Remove __future__ annotation

publish/aliPublish.conf
https://alijenkins.cern.ch/job/Build-MCRelease-O2PDPSuite
CC @sawenzel @ktf
=> Publish MC-prod tags in CVMFS

publish/aliPublish.conf
=> Fix typo on aliPublish

ci/repo-config/macos/osx_arm64/aliroot.env
As discussed with @pzhristov 
CC @ktf
=> Move AliRoot CI on macOS to new ARM cluster

.github/workflows/o2-full-deps.yml, ci/repo-config/DEFAULTS.env, ci/repo-config/mesosci/slc9-gpu/DEFAULTS.env
=> Bump aliBuild in RPMs and CI testers

.github/workflows/o2-full-deps.yml
New one actually never worked.
=> Go back to old way of building RPMs
